### ISSUE TITLE
add DOAP to crosswalk table

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#10]
I just came across DOAP -- Description of a Project, another minimal software description.  This one is reasonably well formalized as an [OWL schema](https://github.com/edumbill/doap/blob/master/schema/doap.rdf).  Project details here:

https://github.com/edumbill/doap

**Comment by cboettig** [comment]
Done in PR  #60

**Comment by cboettig** [comment]
whoops, that's just a placeholder.

**Comment by cboettig** [comment]
DOAP is in the crosswalk: https://codemeta.github.io/crosswalk/doap/
