### ISSUE TITLE
Schema.org missing in the crosswalk mapping

### ISSUE THREAD

**Issue by rajido** [codemeta/codemeta#101]
Include in the crosswalk mapping a column for Schema.org. Schema.org have several types suitable to capture the information proposed by codeMeta. These type are: Code, SoftwareSourceCode and SoftwareApplication.

**Comment by rajido** [comment]
Started to make this mapping. I will make a pull request. You can assign this issue to me.

**Comment by gothub** [comment]
@rajido You can find the schema.org types that CodeMeta is currently using by looking in the
[CodeMeta JSON-LD file](https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld)
and matching entries from the crosswalk column "CodeMeta Field" to the JSON-LD file. (I'll mentioned this in the docs, as now I see that this connection is not at all obvious!)

We used the schema.org terms that were a match to a CodeMeta concept, but had to look to
other schemas for other CodeMeta concepts. Some concepts weren't in any well know schema, so
we mapped those to our own namespace, i.e. https://codemeta.github.io/terms.
