### ISSUE TITLE
Frequently Asked Questions page

### ISSUE THREAD

**Issue by iaine** [codemeta/codemeta#102]
Creating an FAQ file would provide a link to FAQs (what is it, where is it) and I'm sure there are others not in the README. It might be a thought to split into two: developer and service provider?

**Comment by sdruskat** [comment]
Related (sorry for possibly creating a duplicate): #105.

**Comment by mbjones** [comment]
Great idea, and yes I think it is a duplicate of #105 so I am closing this ticket.
