### ISSUE TITLE
Create documentation/FAQ suitable for newcomers

### ISSUE THREAD

**Issue by sdruskat** [codemeta/codemeta#105]
This should probably live outside of README.md (in a separate `docs` folder?).

**Comment by sdruskat** [comment]
A draft:

# CodeMeta FAQ

## What CodeMeta IS

CodeMeta is a "[Rosetta Stone](https://en.wikipedia.org/wiki/Rosetta_Stone)", i.e., a translation medium, for software metadata.

## What CodeMeta ISN'T

- CodeMeta is **not** a new standard! Instead, it is designed to **foster collaboration and interoperability** of metadata standards

## Rationale: Why CodeMeta?

CodeMeta exists to

-  **incentivise** Research Software Engineers and domain scientists developing software to **release their software into the open**
- allow research software to be **cited more easily**
- **increase discoverability** of research software
- allow people to **build tools** that use the metadata, e.g., for indexing, dependency checking, etc.

## Does CodeMeta have a format?

- There is a [JSON-LD representation](../../blob/master/codemeta.jsonld) for CodeMeta.

## What can I do with the CodeMeta format?

- **[Discoverability]** Build a searchable index or repository of [CodeMeta-compatible projects](#what-does-"codemeta-compatible"-mean?)
- **[Discovery]** Easily track and compare dependencies and licenses of [CodeMeta-compatible projects](#what-does-"codemeta-compatible"-mean?)
- **Add your idea here!** 

## What does "CodeMeta-compatible" mean?

???

# Getting started

## Create an implementation

`[TBD]` Link to the spec

## Use a CodeMeta library

`[TBD]` Is there such a thing? This section should include links to source, download, and a tutorial

## Add a new format

Please contact us if you want a new format to be added to CodeMeta.

***WHAT CONTACT DETAILS SHOULD BE LINKED TO HERE?***

# Contribute

Please either contact us, or fork the repository and create a pull request (or both).

# Contributers, funders, acknowledgments, etc.

`[TBD]`

**Comment by mbjones** [comment]
I think the FAQ and other documentation examples are a great idea, and we should strive to have those complete for when the paper comes out, so it can reference them.  So, assigning this to the paper milestone.

**Comment by cboettig** [comment]
We try to address these questions on the homepage now https://codemeta.github.io  (big picture issues on the home-page, technical info in the user and developer guides).  So will close for now, but I would still love to hear from @sdruskat and others if the homepage is a decent answer to all these, or if there are obvious gaps we want to address with a FAQ or similar.   Feel free to re-open this thread (or start a new one) if more attention to some area is needed.
