### ISSUE TITLE
developer-guide.md links to non-existent tutorial

### ISSUE THREAD

**Issue by sdruskat** [codemeta/codemeta#106]
In the first section: 

> Users that only require instructions for manually creating CodeMeta software descriptions may wish to review the **CodeMeta Tutorial**.

**Comment by gothub** [comment]
@sdruskat Thanks for reporting the broken link. I'll post the tutorial to the git repo as soon as
I have a first draft.

**Comment by mbjones** [comment]
We should strive to have this complete for when the paper comes out, so it can reference them.  So, assigning this to the paper milestone.

**Comment by rahulkde** [comment]
@gothub  Is the final draft of the tutorial done

**Comment by cboettig** [comment]
All docs are on the website now (a separate github repo, still all markdown source), rather than this repo.  Developer guide: https://codemeta.github.io/developer-guide/
