### ISSUE TITLE
Handling 'generic' attributes that appear in many places

### ISSUE THREAD

**Issue by Rob-Welch** [codemeta/codemeta#108]
I don't have a proposed solution for this (yet) but I have a really great problem.

Say you have an arbitrary file in an arbitrary format that you want to convert to another format. Let's call them crappyformat1.json and crappyformat2.json.

Your first format has a bit that looks like this
- crappyAttribute
  - description

Your second has a bit that looks like this
- otherCrappyAttribute
  - arbitrarilyNamedDescription

The crosswalk file, as it stands right now, does not specify that it has to map the arbitrarily named description onto the regular description based on the parent.

I have been working on an implementation of conversion between json files (assuming that the crosswalk.csv). Right now, can pull in the crosswalk and schema files, and start looking through the crosswalk files to see if there are any attributes it can match via the crosswalk - but it can't actually match them up. It's inside some attribute somewhere and it doesn't know if both the attribute AND its parents (and its parent's parents or its parent's parent's parent) have different names.

This issue will be very important to the spec writers and guardians of the crosswalk, because this information needs to be included. Preferably in a simple  (e.g. having parent.child entries in the crosswalk). Something more elegant, if you can think of it.

**Comment by gothub** [comment]
@Rob-Welch Here are two potential approaches to conversion to / from the CodeMeta
schema:

- the structure of a CodeMeta description file is detailed in the [CodeMeta JSON Schema](https://github.com/codemeta/codemeta/blob/master/codemeta-json-schema.json), which shows
the parent / child relationships you mentioned. More info on JSON schema can be found [here](http://json-schema.org/). 

- a bit more obscure, but if the file being converted to / from the CodeMeta JSON-LD is also JSON-LD, the conversion from one 'vocabulary' to the other can be performed as detailed in the somewhat [cartoony video](https://www.youtube.com/watch?v=Tm3fD89dqRE) prepared by one of the main JSON-LD designers. I haven't found documentation describing this technique anywhere else.

**Comment by Rob-Welch** [comment]
@gothub Actually, I already load in the CodeMeta JSON Schema. Here is how the script (which is very incomplete) works right now

1) User supplies a schema. Load in the schema, preserving hierarchy. Remove all of the placeholder content. It loads via Python's built in json library right now, into a python dictionary object (structurally identical and can be dumped back into a json file at any time).
2) Load in the crosswalk. Right now it loads into a dataframe using Pandas (that's pretty much the standard way to load tabular data into Python). It will also attempt to load the crosswalk straight from the repo, and if that fails (or if it's incompatible) it will let the user specify one instead.
3) User supplies sample file to be converted.
4) For each attribute in the schema, check if there is a corresponding item in the crosswalk, then if there is a corresponding item in the input file, and if so, load the data. If the attribute is an object, recursively check through the attributes of that object using the lookup table as before.

The problem is, I can't implement the last step right now. The example above shows a situation in which the wrong value could potentially be loaded from the crosswalk.csv lookup table, because the lookup table has no way of indicating that arbitrarilyNamedDescription and description represent the same data, and that the meaning of arbitrarilyNamedDescription and description  changes based on the parent object.

The best way to fix this (in my opinion) would be to alter the lookup table so that it contains cases for

```
crappyAttribute.description
otherCrappyAttribute.arbitrarilyNamedDescription
```
and finally just

`description`
For each format.

So far, I haven't written anything into this script that is specific to the specification - you could plug any pair of json files into it, and it would be able to convert between them. But I DO depend on knowing the structure of the crosswalk file, and the current structure of the crosswalk file combined with a schema does not completely describe how to convert from one format to the other.

Once this issue is fixed, I should be able to get a pull request with my contribution in fairly quickly.

**Comment by gothub** [comment]
@Rob-Welch I'm not quite clear on your use of the [crosswalk table](https://raw.githubusercontent.com/codemeta/codemeta/master/crosswalk.csv). The initial purpose of this file was a place to accumulate 'concepts' related to software descriptions, with potential (not necessarily definitive) mappings of those concepts to other schemas (DataCite, Zenodo, etc). 
I'm not sure if the data in this file is accurate enough to serve as a data file suitable for driving transformations.

The [CodeMeta JSON-LD](https://raw.githubusercontent.com/codemeta/codemeta/master/codemeta.jsonld) file is intended to be the definitive reference for the terms used by CodeMeta. The CodeMeta JSON schema
file is really an auxiliary file that is used because JSON-LD doesn't provide information / validation
of the structure of a CodeMeta file (at least not clearly / easily).

**Comment by Rob-Welch** [comment]
@gothub 
Sorry for the confusion, I left the conference with a very incomplete idea of how the conversion process worked!

I have been assigned to the task of writing a script that converts between some of the target formats (as many as possible, ideally) and can export .bib files. For now, I will rest on my laurels until [the milestone you mentioned](https://github.com/codemeta/codemeta/milestone/5) is done.

**Comment by gothub** [comment]
@Rob-Welch Let me know however I can help in the process. We still have some work to do concerning more useful documentation and tools, so keep checking back to the repo in the
coming weeks.

**Comment by mbjones** [comment]
This discussion leads me to believe that there is nothing left to resolve on this ticket, so closing (reopen it if I missed something).  @Rob-Welch may want to open other tickets describing the conversion scripts he is working on.
