### ISSUE TITLE
Create example 'external' JSON-LD to show conversion to/from CodeMeta JSON instance files

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#109]
It is one of the goals of the project for stakeholder repositories to generate / translate CodeMeta
files into and out of their own systems as shown in this [milestone](https://github.com/codemeta/codemeta/milestone/5).

In order to assist in this process, create an 'external' JSON-LD schema that can be used as an example of using JSON-LD API to convert external JSON files to the CodeMeta instance
file equivalent, using the process detailed in this [video](https://www.youtube.com/watch?v=Tm3fD89dqRE). This process is mentioned in the developer-guide.md, but a complete
working example is needed.

**Comment by cboettig** [comment]
Thanks @gothub for pointing out this excellent video from Manu Sporny (above).  I think it's really a nice example of how JSON-LD is very convenient for doing exactly what we're trying to do with the crosswalk table: translate between different schema which are saying the same thing.  

I've created a few examples of how one uses this Expansion and Compaction methods of JSON-LD to do this, e.g. using the crosswalk table to turn some DataCite data into CodeMeta data, or into Zenodo Data: https://github.com/codemeta/codemetar/blob/master/inst/notebook/translating.md

This example uses the the expansion / compaction routines in R, though they are identical to the routines in json-ld playground (the R package wraps the same javascript library).  Feedback much appreciated; some of the more complex mappings get into some more subtle issues with json-ld. 

cc @arfon @mfenner @mbjones thought you might also like to see json-ld expansion+compaction pattern in action here in crosswalking.  in any event, I definitely recommend the short video Peter mentions if you haven't already seen it: https://www.youtube.com/watch?v=Tm3fD89dqRE .  Super simple/intuitive idea, but at the same time very clever!
