### ISSUE TITLE
Software identifier vs version identifer?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#113]
@mbjones @gothub Maybe you already saw the question posed by @danielskatz at https://github.com/force11/force11-scwg/issues/157, raising the suggestion of assigning two identifiers when code is initially archived; one pointing to the specific version and another to the software as a whole.

I know this is an issue we've discussed quite a bit already, so just wanted to close the loop so that CodeMeta and Software citations working group don't end up making different recommendations in this context.  In particular, this relates to the use of DataCite's `relatedIdentifier` as we discussed on a recent call, see https://github.com/codemeta/codemeta/issues/91)

I did comment on the scwg thread with my impression that we would rather always have a single version-specific identifier, but take a look at my comment and correct me if I'm off there.  Thanks!

**Comment by gothub** [comment]
Can the CodeMeta use of `relatedIdentifier` support the gathering of software citations across
software versions, possibly using the `isNewerVersionOf` relationship?

If yes, then I think this is a better solution then depending on an identifier
type (e.g. DOIs have a parent field) or a repository scheme that allows following the revision history
to find all version of a software package to determine specific identifiers and associated citations.
(DataONE has this type of scheme where the `series identifier` always points to the latest revision of an object, and from there you can trace backward to all previous revisions and the revision specific identifiers)

CodeMeta instance documents might use many identifier types and be stored in many repositories,
so maybe not a good idea to rely on the capabilities of a certain identifier type or repo.

**Comment by mbjones** [comment]
I agree on the version-specific identifier.  With that, and with a isNewerVersionOf type of field, we can do any type of aggregations that we need.  It's much better to keep the relationships in metadata than to encode them in identifiers.

Regarding DataONE, we keep the version chain info in our obsoletes/obsoletedBy fields, which allows one to walk the revision chain in both directions.  This is somewhat orthogonal to SIDs, which are another identifier that is assigned to a version chain and always resolves to the HEAD of that chain.  So, given a SID, one can find the HEAD of the version chain, and then one can walk backwards through the chain using the obsoletes field to get all of the prior versions.  In DataONE, the `obsoletes` field is a synonym to the `prov:wasRevisionOf` property, and is a subProperty of the `prov:wasDerivedFrom` property.  We support using `prov:wasDerivedFrom` in our provenance traces as well as the versioning stuff. Derived data are more loosely coupled to their original, and often represent amalgams where the derived product combines and transforms multiple original sources, but is not specifically meant to replace the original.  I think similar relationships exist in in software, and using PROV predicates in our metadata would be very powerful.

**Comment by mbjones** [comment]
@gothub and I discussed this today, and we agreed that the `relationships` field is the right place to specifiy the version relationships among identified versions of the software.  The main change we propose is to 1) be explicit about the `relationshipType` property so it is clear what namespace the property comes from, and 2) recommend that we use the W3C PROV vocabulary for relationship types whenever possible, as these are standardized and widespread.  In particular, to specify the version relationships, one would use [prov:wasRevisionOf](https://www.w3.org/TR/prov-o/#wasRevisionOf) to list the earlier version of the software, and one would put the prov namespace in a new `namespace` field. For example:

```json
"relationships": {
        "relationshipType": "wasRevisionOf",
        "namespace": "http://www.w3.org/ns/prov#",
        "relatedIdentifier": "urn:uuid:F1A0A7AF-ECF3-4C7D-B675-7C6949963995",
        "relatedIdentifierType": "UUID"
}
```

Unless @cboettig or others have suggested alternatives, @gothub is going to work on implementing this and we can move forward.

**Comment by cboettig** [comment]
Nice, this looks great to me. I like the use of prov in the relationships too.

**Comment by gothub** [comment]
These properties have been documented in https://github.com/codemeta/codemeta/blob/master/developer-guide.md. No additional changes to this property have been proposed.
