### ISSUE TITLE
are additions to the crosswalk welcome?

### ISSUE THREAD

**Issue by mr-c** [codemeta/codemeta#115]
Happy to add the AppStream, an "Infrastructure for distro-agnostic software-centers and software metadata handling" to the crosswalk if so.

https://www.freedesktop.org/software/appstream/docs/
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by mbjones** [comment]
Yes, new crosswalks are appreciated.  Please provide a pull request to add a new column to the crosswalk table.  The rest of the crosswalks have been repeatedly reviewed by multiple people, so please be precise in your mappings. Thanks!

**Comment by cboettig** [comment]
Closing as stale, but pull requests crosswalking any other vocabulary are always welcome. 

Note that the crosswalk is now more explicitly aligned to `schema.org` terms, in many cases any existing mapping into `schema.org` should work "out-of-the-box" in the codemeta context.  Also, see the visualizations of the crosswalk by column on our website, which might be easier to read:  https://codemeta.github.io/crosswalk/
