### ISSUE TITLE
CodeMeta format type for DataONE

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#116]
@mbjones  We have discussed having a permanent identifier that functions as the document
format identifier that is required when an object is uploaded to DataONE. We would have
a DOI, minted vis EZID that would have a CodeMeta version included with this format:

```
http://doi.org/10.xxx/schema/codemeta-1.0
```

We have an absolute dependency on github, as our context file is housed there, and every
CodeMeta document needs to reference it. So I'm a little unclear why we need a DOI and 
can't just use the context for the DataONE 'formatId', that will include a tagged version of the repo:

```
"@context": "https://raw.githubusercontent.com/codemeta/codemeta/0.1-alpha/codemeta.jsonld"
```

**Comment by mbjones** [comment]
My main argument is permanence.  By using a DOI, we gain a layer of indirection.  If (and when) github changes their URL format, we simply can update the DOI resolution.  If JSON-LD parsers know how to handle redirects, it would probably be best to use a release DOI for the context as well.

**Comment by gothub** [comment]
Yep, agreed. The best case would be that the DOI used for the `@contexst` would be the
same value used for `formatId` in a DataONE sysmeta object that DataONE uses to
determine how to index the document.

Could we go ahead and setup the DOI so I can test if JSON-LD will handle a redirect for 
a context file? Or do we have to wait until the official version is tagged?

**Comment by mbjones** [comment]
We can set up a DOI using the KNB generateIdentifier service, and then
point it at the github location using the EZID web interface.  Then later
you can change it when you tag it.

Matt

**Comment by gothub** [comment]
@mbjones Tests of using a CodeMeta DOI for the context value have not worked. It appears that the 
JSON-LD API does not handle redirects correctly. I'll log an issue with the JSON-LD git
repo for this.

This is unfortunate, as it would have been really clear to use the same DOI for the
@context value and the formatId for DataONE sysmeta.

Is there a way to resolve this CORS issue? You can specify access with .htaccess, but not sure
how that is going to help us. Wouldn't the CORS access need to be either implemented in the
JSON-LD API code, or an .htaccess on the DOI resolver hosts? I don't have alot of experience with
this, and haven't seen the same problem on the JSON-LD boards and git repo.

Here is the relevant portion of a test CodeMeta document, and the resulting JSON-LD playground
error:

```
...
   "@context":"http://doi.org/10.5072/FK2/schema/codemeta-0.9",
   "@type":"SoftwareSourceCode"
...
```

JSON-LP playground error for this document:

```
{
  "stack": "Error\n    at JsonLdError (http://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:2358:19)\n    at done (http://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:6741:19)",
  "name": "jsonld.InvalidUrl",
  "message": "Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.",
  "details": {
    "code": "loading remote context failed",
    "url": "http://doi.org/10.5072/FK2/schema/codemeta-0.9",
    "cause": {
      "stack": "Error\n    at JsonLdError (http://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:2358:19)\n    at Object.error (http://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:1718:18)\n    at j (http://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1265:27136)\n    at Object.fireWith [as rejectWith] (http://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1265:27949)\n    at x (http://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1267:22269)\n    at XMLHttpRequest.b (http://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1267:26298)",
      "name": "jsonld.LoadDocumentError",
      "message": "URL could not be dereferenced, an error occurred.",
      "details": {
        "code": "loading document failed",
        "url": "http://doi.org/10.5072/FK2/schema/codemeta-0.9",
        "cause": ""
      }
    }
  }
}
```

**Comment by mbjones** [comment]
@gothub I'm wondering if that is just an artifact of working on the LD playground? Have you tried it with a validator that you control directly?  The playground will need to protect against additional CORS issues than one where we handle the parsing on the same host that we receive the requests.

**Comment by cboettig** [comment]
I think we can close this in favor of #125 ?

**Comment by gothub** [comment]
@cboettig Yes, this conversation is now in https://github.com/codemeta/codemeta/issues/125

Closing as duplicate of https://github.com/codemeta/codemeta/issues/125
