### ISSUE TITLE
Complete JSON-LD context for codemeta

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#12]
The current context file is incomplete.  Need to finalize handling of dependency elements and a few of the other fields.

**Comment by gothub** [comment]
The context file is complete as of commit 6aa13e996fab36c324083c2c3af139ec26c53674, meaning there are no currently known needed additional terms or problems. This version is
ready for review, which of course could likely result in proposed changes. Last change to the
context file was made in commit 6aa13e996fab36c324083c2c3af139ec26c53674
