### ISSUE TITLE
Try parsing json-ld in R with ropensci/jsonld

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#122]
@gothub @mbjones ,

@jeroenooms has just put together an R package for working with jsonld, wrapping around the official javascript library: https://github.com/ropensci/jsonld

The README shows some examples of contracting / expanding and rendering to RDF, which might be helpful for our CodeMeta work (particularly on the R package side; though I also wonder if it might help us move the CI unit testing into R rather than Ruby, since we're probably all more familiar with that, though not a necessity).  

Jeroen mentioned that there's some Ajax code in the jsonld.js library that isn't supported by his V8 engine for working with javascript source from R; so I suppose it's possible the package has some hiccups accessing external, web based schemas, (though maybe we can work around that with some additions to the jsonld package if it is even an issue).  Hoping to flush out with some more real-world testing.

**Comment by gothub** [comment]
@cboettig @jeroenooms This looks really good and will certainly help with authoring and validating json-ld documents in R.

**Comment by cboettig** [comment]
We can do this in the planned codemeta R package (D7, for generating/working with codemeta for R software), so closing this out here.
