### ISSUE TITLE
New 'json-ld' ruby gem causes build to fail

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#123]
Recent builds of the 'json-ld' ruby gem cause the test suite to fail. This first showed up in the
Travis CI build, but has been recreated locally on my machine. I've temporarily updated the
'Gemfile' so that the new build is not loaded. So these tasks need to be performed:

- [ ] log an issue in the repo: https://github.com/ruby-rdf/json-ld and post the issue number here
- [ ] update the Gemfile to not specify a max rev number for json-ld when a fix is available

**Comment by cboettig** [comment]
Would it be worth migrating the test into R instead, now that we have both [jsonld](https://github.com/ropensci/jsonld) and [jsonvalidate](https://github.com/ropensci/jsonvalidate) support in R?

**Comment by gothub** [comment]
@cboettig I entered issue https://github.com/codemeta/codemeta/issues/124 to assist in considering this. For my time allocation, I think this is lower priority that the current items on the [D5](https://github.com/codemeta/codemeta/milestone/2), [D6](https://github.com/codemeta/codemeta/milestone/3) milestones

**Comment by cboettig** [comment]
Good point, sounds good. Meanwhile your current workaround is probably fine as it is.

**Comment by cboettig** [comment]
I think this is deprecated, as we now perform automated checks in R (though most of these are currently running in the `codemetar` travis file, they run against the codemeta.jsonld schema here.  They should probably migrate over here as well, but that's a separate issue.  closing this as deprecated.
