### ISSUE TITLE
Crosswalk to/from DOI metadata

### ISSUE THREAD

**Issue by mfenner** [codemeta/codemeta#126]
I have started a new command-line tool that converts DOI metadata (Crossref, DataCite) to and from other formats, in particular schema.org/JSON-LD: https://github.com/datacite/bolognese. I wonder how this work can best be aligned with the codemeta schema. 

I am particularly interested in a seamless metadata extraction/conversion given a GitHub repository or release URL (which means grabbing some metadata from GitHub and the rest from a standard JSON or YAML file in the repository). One important use case is the automatic generation of DataCite metadata that can be used for DOI registration.

**Comment by mfenner** [comment]
I have minted the first DOI using codemeta metadata in `codemeta.json` in repository root. Generated DataCite metadata via `bolognese https://github.com/datacite/maremma -t datacite`, after installing `bolognese` gem.

**Comment by mfenner** [comment]
I have launched an updated DataCite DOI Content Negotiation to stage today. One new feature is support for codemeta for any DataCite DOI for software, e.g. using a random recent DOI from Zenodo:

```
https://data.test.datacite.org/application/vnd.codemeta.ld+json/10.5281/ZENODO.546753
```

The codemeta support can obviously improved, but this also depends on the richness of the DataCite metadata.

**Comment by augustfly** [comment]
Is relatedIdentifier/relationships/additionalType support blocked in anyway?

**Comment by mfenner** [comment]
No, the codemeta support is work in progress. RelatedIdentifier support is already in underlying library. You can open an issue at https://github.com/datacite/bolognese, but I will make sure to add that support.

**Comment by cboettig** [comment]
Thanks @mfenner .  I think this should all be streamlined significantly by the adoption of version 2 with the alignment to `schema.org`.  

Stuff you've already written based on `codemeta-v1` should be fine as long as it uses the DOI for the `v1.0` release in the context.  Hope to have a tagged release for the new context soon.
