### ISSUE TITLE
From SWH archive- questions about DOAP, SEON, debtags, ADMS.SW, Wikidata, generators and statistics..

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#127]
First of all let me say that the CodeMeta project is a blessing for understanding
and implementing metadata standards regarding software.

I'm a research intern at [Software Heritage](https://www.softwareheritage.org/) which collects the source code of software projects from a variety of origins. The same source code can be collected from different origins, each providing potentially complementary or conflicting metadata describing the project of which this source code is part, and the people that take part in it.

During the brief research I have conducted over metadata schemas for software projects, there are a
few questions I have in mind for the CodeMeta community:

1. In the crosswalk table the standards bellow are omitted, is there a reason for this omission or just a lack of working hands to add them in? 
  - [x] DOAP
  - [ ] ADMS.SW
  - [ ] debtags 
  - [ ] [SEON ](http://www.se-on.org/ ) (A family of Software Evolution ONtologies)
  - [x] [Wikidata software properties](https://www.wikidata.org/wiki/Wikidata:WikiProject_Informatics/Software#Properties)
   
2. Looking at the ontology, you use schema.org terms, but the schema.org ontology isn't included in the comparison in the crosswalk table. Why ?

3. I was really excited when I found Afron's CodeMeta generator. Are there more tools for
generating or parsing metadata files from one standard to codemeta.json?

4. Do you have statistics about the usage of CodeMeta or any other standards in Github or in general?

5. How can I help?

Thank you for any light you can shed on these dark spots.
Morane

**Comment by mbjones** [comment]
@moranegg Glad its looking useful to you.  Regarding your questions...

- We welcome additional crosswalks.  We've wanted to do DOAP (issue #10) and ADMS.SW (issue #41), but haven't gotten there.  Is debtags the same things as the Debian package format?  If so, that is already in the crosswalk.  Hadn't come across SEON, probably should enter a ticket for that one.  And had thought about Wikidata software, that would be good to add too.
- We've been mapping everything *to* schema.org properties, so we felt it was redundant to include it in the table, but it probably wouldn't hurt.
- His generator is great.  I don't think it produces the most recent version of CodeMeta, so it needs to be patched up for that.  We are working on a generator in R to allow people to upload codemeta to data repositories from R.  Other tooling efforts are definitely welcome.
- Nope, haven't collected any stats.
- We welcome all help. Mappings, documentation, tool development.  It would be really useful to bring Arfon's tool forward to the released version 1.0.  But we'd welcome any contributions you want to make.

**Comment by moranegg** [comment]
@mbjones  thanks for the detailed response.

As for debags: Although it is not the debian package format, neither is it actually a standard.
Debtags are terms used to describe in a non-formal way. Here's a link for the current vocabulary https://anonscm.debian.org/cgit/debtags/vocabulary.git/tree/debian-packages.

I will add the vocabularies I come across during the next few weeks.

**Comment by cboettig** [comment]
@moranegg Thanks for all your contributions so far!  More edits to crosswalk are welcome.  
Realizing we didn't link to said R generator for codemeta, package overview is here: https://codemeta.github.io/codemetar/ .
