### ISSUE TITLE
Use framing instead of json-schema to specify tree structure

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#128]
Since JSON-LD is linked data, there are lots of possible json structures that correspond to the same set of information (e.g. the same raw collection of triples).  When consuming the data programmatically, it is of course really helpful to have the JSON data in a sensible tree-like structure (e.g. role should be a branch of an agent).  To guarantee a predictable layout, rather than put this obligation on the creator of the `codemeta.json` by insisting json validate against some schema, we can simply provide a "frame" which will transform the data provided into the desired tree structure so that our program can always access the data in this sensible way (e.g. `code$agent[[1]]$role`).  Of course since this approach must work with whatever data is provided, there's no notion of enforcing 'required' fields.  On the other hand, additional fields in the codemeta.json that are not recognized by the frame can be automatically included anyway or ignored, depending on how we write the framing.  For illustrative purposes I've written this example frame to drop anything we don't explicitly request:

e.g. here is a [playground example](http://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22_%3Ab0%22%2C%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fidentifier%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22http%3A%2F%2Fdx.doi.org%2F10.6084%2Fm9.figshare.828487%22%7D%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22CodeMeta%2C%20a%20minimal%20convention%20for%20software%20metadata%22%7D%2C%22http%3A%2F%2Fschema.org%2Fagent%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0003-0077-4738%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-3957-2474%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-2192-403X%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FcodeRepository%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FURL%22%2C%22%40value%22%3A%22https%3A%2F%2Fgithub.com%2Fcodemeta%2Fcodemeta%22%7D%2C%22http%3A%2F%2Fschema.org%2FdateCreated%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%2C%22%40value%22%3A%222014-08-06%22%7D%2C%22http%3A%2F%2Fschema.org%2FdateModified%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%2C%22%40value%22%3A%222014-08-15%22%7D%2C%22http%3A%2F%2Fschema.org%2FdatePublished%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%2C%22%40value%22%3A%222014-09-06%22%7D%2C%22http%3A%2F%2Fschema.org%2Fdescription%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22Codemeta%20is%20a%20metadata%20content%20standard%20for%20software.%20%20It%20includes%20schemas%20in%20JSON-LD%20and%20XML%20Schema%20for%20providing%20semantics%20and%20validation.%22%7D%2C%22http%3A%2F%2Fschema.org%2Fkeywords%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22publishing%2C%20DOI%2C%20credit%20for%20code%22%7D%2C%22http%3A%2F%2Fschema.org%2Flicense%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22Apache-2.0%22%7D%2C%22http%3A%2F%2Fschema.org%2Frequirements%22%3A%5B%7B%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FURL%22%2C%22%40value%22%3A%22https%3A%2F%2Fdx.doi.org%2F10.6084%2Fm9.figshare.1164194.v13%22%7D%2C%7B%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FText%22%2C%22%40value%22%3A%22python%20version%202.7.10%20or%20higher%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fversion%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%222.1.0-rc.2%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FuploadedBy%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0003-0077-4738%22%7D%7D%2C%7B%22%40id%22%3A%22_%3Ab1%22%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2Fnamespace%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22http%3A%2F%2Fwww.ngdc.noaa.gov%2Fmetadata%2Fpublished%2Fxsd%2Fschema%2Fresources%2FCodelist%2FgmxCodelists.xml%23CI_RoleCode%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FroleCode%22%3A%5B%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22originator%22%7D%2C%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22resourceProvider%22%7D%5D%7D%2C%7B%22%40id%22%3A%22_%3Ab2%22%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2Fnamespace%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22http%3A%2F%2Fwww.ngdc.noaa.gov%2Fmetadata%2Fpublished%2Fxsd%2Fschema%2Fresources%2FCodelist%2FgmxCodelists.xml%23CI_RoleCode%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FroleCode%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22copyrightHolder%22%7D%7D%2C%7B%22%40id%22%3A%22_%3Ab3%22%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2Fnamespace%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22http%3A%2F%2Fwww.ngdc.noaa.gov%2Fmetadata%2Fpublished%2Fxsd%2Fschema%2Fresources%2FCodelist%2FgmxCodelists.xml%23CI_RoleCode%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FroleCode%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22contributor%22%7D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-2192-403X%22%2C%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FPerson%22%2C%22http%3A%2F%2Fschema.org%2Faffiliation%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22NCEAS%22%7D%2C%22http%3A%2F%2Fschema.org%2Femail%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22slaughter%40nceas.ucsb.edu%22%7D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22Peter%20Slaughter%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FRole%22%3A%7B%22%40id%22%3A%22_%3Ab3%22%7D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0002-3957-2474%22%2C%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FOrganization%22%2C%22http%3A%2F%2Fschema.org%2Femail%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22info%40ucop.edu%22%7D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22University%20of%20California%2C%20Santa%20Barbara%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FRole%22%3A%7B%22%40id%22%3A%22_%3Ab2%22%7D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Forcid.org%2F0000-0003-0077-4738%22%2C%22%40type%22%3A%22http%3A%2F%2Fschema.org%2FPerson%22%2C%22http%3A%2F%2Fschema.org%2Faffiliation%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22NCEAS%22%7D%2C%22http%3A%2F%2Fschema.org%2Femail%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22jones%40nceas.ucsb.edu%22%7D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%22%2C%22%40value%22%3A%22Matt%20Jones%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FRole%22%3A%7B%22%40id%22%3A%22_%3Ab1%22%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FisMaintainer%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23boolean%22%2C%22%40value%22%3Atrue%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FisRightsHolder%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23boolean%22%2C%22%40value%22%3Atrue%7D%2C%22https%3A%2F%2Fcodemeta.github.io%2Fterms%2FmustBeCited%22%3A%7B%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23boolean%22%2C%22%40value%22%3Atrue%7D%7D%5D%7D&frame=%7B%22%40context%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2Fcodemeta%2Fcodemeta%2Fmaster%2Fcodemeta.jsonld%22%2C%22%40type%22%3A%22Code%22%2C%22%40explicit%22%3A%22true%22%2C%22dcterms%3Atitle%22%3A%7B%7D%2C%22schema%3Adescription%22%3A%7B%7D%2C%22agents%22%3A%7B%22%40type%22%3A%5B%22person%22%2C%22organization%22%5D%2C%22%40explicit%22%3A%22true%22%2C%22name%22%3A%7B%7D%7D%7D)  which uses a simple frame to filter and transform a flat representation of codemeta json-ld triples describing the agents into a json tree containing only requested fields and nesting the agent properties.

**Comment by cboettig** [comment]
A few examples of this in R are now shown in the draft vignette on jsonld-framing for the codemetar package: http://localhost:8787/files/Documents/research/code/cboettig/codemetar/docs/articles/JSON-LD-framing.html

**Comment by mfenner** [comment]
@cboettig can you explain the use cases where framing would help? In my understanding framing is a link data concept, needed for unambiguously converting a JSON tree into a graph. I am not sure how central this is to a software metadata crosswalk, which in my understanding should be possible without knowing anything about linked data.

**Comment by cboettig** [comment]
@mfenner Thanks for all your help on the issues, great to have your experience & perspective on these things.  

Re framing: the use case would be as an alternative to expecting users to validate their own codemeta.json files against our schema.  I'm just trying to play by the book: we've declared that codemeta.json *is* linked data, so I believe that it is reasonable for a user to assume they can do the usual json-ld things, like using a flat graph with reference ids or a nested graph, or extending the data model with other linked data strings and not have to validate against a specific tree format of our schema.  I think this makes things simpler for a user without knowledge of linked data too, in that they likewise don't have to worry about validation and the formatting is a bit more forgiving.  

Of course this means that someone consuming the codemeta.json has the extra responsibility of first applying the frame rather than just assuming the data already matches the schema.  Ultimately that gives such developers more flexibility, but of course I acknowledge it's shifting some burden from those generating the json to those consuming it, which was ever the trade off.

I'm not set on framing, it just seemed like it was the json-ld way of solving the problem we were addressing with json-schema, and folks seemed pretty keen on going with json-ld and not json schema or xml schema as our data model.

**Comment by mfenner** [comment]
@cboettig I didn't know that you made the decision that codemeta *is* linked data. Is there a Github issue or other place where I can read up on the reasoning behind this? Obviously JSON-LD describes linked data, but you can also use JSON-LD without going all the way down this path. If I am not mistaken, most metadata standards relevant for software are not linked data.

**Comment by cboettig** [comment]
@mfenner Thanks.  No, I don't think we ever flushed out so precisely the positives and negatives of going with linked data vs some other route.  Going into the workshop we seemed to have a consensus that we were going to be writing a json-ld context file; and maybe the rest is just my confusion, it seemed to me that this involved the `codemeta.json`were going to declare and use that context and thus be valid json-ld.  I don't have much experience in this, so I'm not familiar with examples that go about defining JSON-LD context files but not "going all the way down this path".  

I don't think I'm trying to push people down any particular path; we have the schema file already and I think that's not a bad thing.  I don't see creating some example frames as being particularly prescriptive, if anything I thought the general idea of this approach was to be less prescriptive and more flexible. To me at least it looked like we had written some linked data so it made sense to try and operate on it as linked data.

**Comment by cboettig** [comment]
I've added examples of how framing provides similar checks to validation here: https://codemeta.github.io/codemetar/articles/validation-in-json-ld.html


I think JSON-LD eliminates some of the issues associated in working with JSON without a validator, which sidesteps, rather than really answering, some otherwise challenging issues where we really didn't have consensus (e.g. we never had consensus on what properties should be "required"; JSON-LD leaves this up to the application developer).

Of course there's still some very good use cases, e.g. a user wants to make sure they don't have a typo in some property name in their file, or that they didn't include some term that is outside of the codemeta context by mistake (though they can extend codemeta at will, by adding their own additional context).  A check that the input file compacts all names (no `:` in compacted property names) does this.
