### ISSUE TITLE
Add DataCite Schema to the crosswalk table?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#13]
One advantage the integrated Github -> Zenodo workflow seems to offer is that, in being assigned a DOI, the software is also then indexed, with metadata, in DataCite.  Since we can query the DataCite API this seems like it would offer a plausible solution to a software discovery index (a la NIH's proposal for such an index, http://softwarediscoveryindex.org/).  

So, perhaps the [DataCite schema](https://schema.datacite.org/meta/kernel-3/index.html) should also get a column on the crosswalk chart, to help track what metadata does and doesn't make it this far down the Github->Zenodo->DataCite pipeline (or any other pipeline that leads software to a datacite DOI). 

Unfortunately, it seems the data that currently gets through this pipeline is pretty small (from a random example of software in zenodo: http://data.datacite.org/application/vnd.citationstyles.csl+json/10.5281/zenodo.15094).

**Comment by cboettig** [comment]
Whoops, my closing example queried for metadata in citeproc-json style rather than in the natural datacite XML schema.  The latter does a better job of correctly including most of the available metadata, e.g.  http://data.datacite.org/application/vnd.datacite.datacite+xml/10.5281/zenodo.15094 which at least declares that this is software and includes the related identifiers. All the more reason to include DataCite schema in the crosswalk.  time to fork...

**Comment by mbjones** [comment]
Adding DataCite to the mapping sounds great, @cboettig I haven't had time to really focus on this crosswalk, but I think a modest amount of work would allow us to reach consensus on the mapping and a proposal as to a core minimum set of fields for software and an optional set.  I think one of the biggest contributions we could make is to propose a __language-neutral__ syntax for expressing software dependencies.  Right now, every packaging system has it (e.g., .deb, R, etc), but they all assume the names are drawn only from their packaging system.  So, simply adding a scope for the dependency names might allow the dependencies to be listed in more generic software descriptions like DataCite metadata.

**Comment by mbjones** [comment]
@JEK-III began the DataCite mapping.  Needs review.

**Comment by cboettig** [comment]
DataCite schema is now in the crosswalk.  (Will need to revisit when next version of that schema is released).
