### ISSUE TITLE
Implement R package for generating codemeta.json

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#131]
@mbjones @gothub I've started an R package to generate codemeta.json from those terms cross-walked from a DESCRIPTION file.  It's super simple so far, (e.g. no way to add additional metadata not provided in DESCRIPTION, no utilities for working with existing codemeta.json).  It does include a unit test validating the output against the json schema that Peter wrote for codemeta.  See https://github.com/codemeta/codemetar, feedback welcome.

**Comment by mbjones** [comment]
I saw you start that -- awesome.  Will take a look in more detail next week.

**Comment by cboettig** [comment]
Closing this out, details now at https://github.com/codemeta/codemetar
