### ISSUE TITLE
Reducing differences between schema.org and codemeta

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#134]
Hi @mbjones @gothub @danielskatz @npch @arfon, others

Been thinking about @mfenner's comments about standardizing a bit more tightly to schema.org.  Would really like group input, but personally I find Martin's suggestion very compelling, particularly in light of related working groups. While personally I don't think codemeta should be restricted to schema.org vocabulary, I do think it would be nice if a schema.org software description was approximately a subset of codemeta.  

For starters, our current spec differs from schema.org in some ways that seem relatively arbitrary, where I think we could standardize more easily:

codemeta      |   schema         | comments
------------------|---------------------|----------------
licenseId       | license              | Schema uses URL, suggest we do so too
controlledTerms | keywords    |   Not sure precisely how this differs from Tags.  (seems to be Categories, but doesn't reference a controlled vocab list?)
tags                   | keywords    |   Seems "keywords" should suffice?
downloadLink    | downloadUrl | Not sure why we've used something different
person               | Person          | types (classes) are upper case in schema
organization     | Organization   | ditto
depends           | softwareRequirements | the schema term is a list of URLs only, while ours is more general

Additionally, we could eliminate our use of `dcterms` terms in place of equivalent `schema.org` terms, for: 

- `dcterms:identifier` could become `schema:identifer`
- `dcterms:title` -> `schema:title`

We also re-type a lot of schema.org terms using XSD types, which also seems needlessly complicated. e.g. we use `xsd:string` instead of `schema.org:Text`.  It might make sense to keep to the XSD versions if we write out an actual XSD schema for an XML version of codemeta (though presumably it would be better to declare the schema.org types match their the xsd types and the validator could still figure things out?), but in our JSON-LD context file this appears confusing.  (Or maybe there's some other good reason for XSD types that I'm missing).  

We should also give some thought to some more subtle differences in recognized properties of codemeta types as compared to schema types:  e.g. `schema:programmingLanguage` does't include `version`. Likewise  schema:softwareRequirements` is not technically a property of a `schema:SoftwareSourceCode` object but only of a `schema:SoftwareApplication` object.   I'm not sure that it really matters what properties schema.org associates with a type, e.g. I'm not sure if there's any problem in having something like:

```json
{
"@context": { "@vocab": "https://schema.org" },
"@type": "programmingLanguage",
"@name": "Python",
"@version": "2.7"
}
```

Conversely, schema.org softwareSourceCode and softwareApplication types do recognize additional properties that codemeta does not have, presumably it should not be a problem if a user includes these.  

In the same way, a user should be able to specify the additional concepts introduced by the codemeta project that have no immediate analog in schema.org.  

(My contention is that it is never an issue as long as the consumer develops their application appropriately for json-ld input).

**Comment by mfenner** [comment]
@cboettig thanks for looking into this, and your arguments make sense. My approach with mapping metadata for datasets to schema.org so far has been to use what exists, and that gets me 90% of the way. For the remaining 10% it then makes sense to open an issue in the schema.org Github repo. 

In half the cases I was then shown how this can be done with the existing schema. It is for example ok to use a property that is not listed with a particular schema type, e.g. `isPredecessor` and `isSuccessor` to link to previous/next version, even thought that property is defined for `productModel`.  So I think it is ok to use `version` with `programmingLanguage`. Another example is `@reverse`, which allows the description of inverse relations. I use this with `citation`, as there is no property for `isCitedBy`, similarly `isBasedOn`.

At the end there will be a few unresolved issues remaining. Which could either lead to a pull request and discussion with the schema.org community, or codemeta goes a different direction. Case in point is https://spdx.org/ for license information, which I find an attractive alternative to using a license URL.

I like the idea of schema.org descriptions for software as a subset of codemeta. And the two could merge at some point in the future, as has for example happened with Good Relations: http://blog.schema.org/2012/11/good-relations-and-schemaorg.html.

**Comment by cboettig** [comment]
> It is for example ok to use a property that is not listed with a particular schema type, e.g. isPredecessor and isSuccessor to link to previous/next version, even thought that property is defined for productModel

Thanks!!! That makes sense but I've been trying to find that clearly stated somewhere for the past hour ;-).  You made my day.

Re: SPDX, right, I think we basically agreed CodeMeta should use SPDX abbreviations for licenses rather than URLs, and I agree that's appealing (e.g. since people might use different URLs to refer to the same general LICENSE file, e.g. do I link the MIT License template or the specific License file with my name on it in my github repo).  But if a URL is good enough for all those using schema.org I'm fine with that too.  

This does beg a related question to the one you answered above: how bad form is it to use an existing property with the wrong type?  e.g. using schema.org's license property but declaring it to be a text string (SPDX string) instead of a URL:

```
"license": {
  "@id": "schema:license" ,
  "@type": "schema:Text"
```

would it be better not to reference `schema:license` in this case?  Here we would be changing a data type, which seems particularly bad form, but maybe not.  Other places we just want to change a node type, (e.g. we want something more structured than `schema:Text` or URL for `softwareRequirements`) which seems less bad since json-ld doesn't perform any coercion on node types.

**Comment by cboettig** [comment]
Just for discussion fodder I've started drafting a proposal for what codemeta.jsonld context would look like if revised along these lines:

I've clustered terms inherited from `schema:SoftwareSourceCode` and `schema:SoftwareApplication` at the top, followed by those additional terms which codemeta would add.  I've also synchronized the names and types a bit as proposed up top.  

One additional non-trivial change to both better align with schema.org and also make more semantically accurate statements is the removal of `agent` structure (along with its role/namespace types) in favor of a handful of role-based properties from schema.org: `author`, `contributor`, `copyrightHolder`, as well as the additional non-schema property of `maintainer`.  We can clarify in the documentation that the use of `author` signals "mustBeCited" while "contributor" does not, since I believe this accurately reflects current usage of these terms in the research community (?).  (Note that schema.org includes both `author` and `creator` and defines them to mean precisely the same thing; I think we are best focusing on author).  

If we adopted these revisions, I think this would achieve making descriptions based solely on `SoftwareSourceCode` into reasonable subsets of `codemeta` descriptions, and a parser designed for one could just as easily parse the the other (while dropping terms it did not know), which I think is a desirable feature.

**Comment by cboettig** [comment]
whoops, forgot link: https://github.com/codemeta/codemeta/blob/master/codemeta-v2.jsonld

**Comment by danielskatz** [comment]
This seems reasonable to me.

**Comment by arfon** [comment]
> I do think it would be nice if a schema.org software description was approximately a subset of codemeta.

👍 I strongly support this. Your suggested modifications look great @cboettig

**Comment by mfenner** [comment]
@cboettig a reference from the schemaorg issue tracker regarding using properties with other classes: https://github.com/schemaorg/schemaorg/issues/1476. @darobin might be able to clarify this more.

**Comment by mfenner** [comment]
And I agree that roles needs more work, and there are different direction this could take. If it is a very small and well-defined list of roles, then adding them as properties looks good. If we want a more person-centric view, then keeping them with the `agent`makes sense. And ideally you want to allow both views. And yes, `author` and `creator` are aliases in schema.org, with `author` probably more widely used.

As part of this discussion you also want to think about metadata outside of software. DataCite is clearly going down the schema.org path, as is http://researchgraph.org/ and BioCaddie (life sciences data). ORCID and Crossref have at least expressed interest. Having something that can be easily aligned with these efforts would make a lot of sense to me.

**Comment by danielskatz** [comment]
Regarding roles, I would (ideally) like to start with the Project CRediT contributorship roles (http://dictionary.casrai.org/Contributor_Roles) and fix them to work for software projects.

**Comment by mfenner** [comment]
And the question that might that started this discussion is whether codemeta could be a building block for the new [Force11 Software Citation Implementation WG](https://www.force11.org/group/software-citation-implementation-working-group), and the answer seems to be **yes**, in the sense that the group could discuss how codemeta could be part of a larger workflow.

**Comment by mfenner** [comment]
@danielskatz +1 regarding CREDIT. We have similar issues with contributor roles for datasets, as the available roles might need to be adapted.

**Comment by cboettig** [comment]
Great suggestions here, thanks!  Sounds like there's a need to think about a good JSON-LD representation of contributor roles that could be shared by both codemeta and related efforts.  Unfortunately the way to annotate roles seems non-trivial to me (see #135 ), particularly if doing so in a way that is also consistent with maintaining the simple schema:SoftwareSourceCode (or really any schema:CreativeWork) as a valid sub-type.

**Comment by mfenner** [comment]
Feel free to add info about how codemeta could be a building block for software citation implementation here: https://github.com/force11/force11-sciwg/issues/4, as the working group will get started in a few weeks.

**Comment by cboettig** [comment]
Alignment done, now tagged as 2.0
