### ISSUE TITLE
technical semantic issue with agent structure?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#135]
The way in which we define roles for `agent` seems at odds, or at least much more ambiguous then, the way in which these roles are communicated in a schema:SoftwareSourceCode object.

Essentially, our structure says that `SoftwareSourceCode` has a property `agent`, and that agent has property `role` which has the value `contributor`.    I believe this is technically ambiguous in that it does not truly assert that `agent` contributed to `SoftwareSourceCode`, only that they, in some capacity, hold the `role` of `contributor` (in much the way they hold the `affiliation` of `NCEAS` etc).

Meanwhile, the listed properties of `SoftwareSourceCode` over at `schema.org` are a lot more explicit about this.  They say that `SoftwareSourceCode` has a property `contributor`, where a `contributor` value must be something of type `Person` or `Organization`.  I believe this is more explicit / technically precise.

In many cases I think it is also a little more intuitive to read or write something like 

```
author: {
  "name": "Carl Boettiger",
  "email": "cboettig@ropensci.org"
}
```
than it is to write

```
agent: [{
  "name": "Carl Boettiger",
  "email": "cboettig@ropensci.org",
  "role": ["aut"]
}]
```

Note that in this construction, assigning multiple roles is obviously a bit more messy, but does benefit from having  `@id`, (something we already have with `uploadedBy`.  e.g. one would identify an individual as the `author`, `creator`, and `copyrightHolder` as follows:

```
"author":
    {
        "@id": "http://orcid.org/0000-0002-1642-628X",
        "@type": "person",
        "givenName": "Carl",
        "familyName": "Boettiger",
        "email": "cobettig@gmail.com",
        "affiliation": "UC Berkeley"
    }
    ],
    "copyrightHolder": {
     " @id": "http://orcid.org/0000-0002-1642-628X
     },
    "creator": {
     " @id": "http://orcid.org/0000-0002-1642-628X"
    },
```

Programmatically there's nice things about the latter as well, e.g. to determine the copyright holder(s) of some `softwareSourceCode` I don't parse a sub-field of the agent's list, but query the copyrightHolder field of the `softwareSoureCode` directly.  And as I've expressed in agreement with @mfenner, I see benefit to doing things in a way that best aligns with schema.org and hense the related efforts he mentions.

Though probably the most compelling reason to drop our agent->role structure is the semantic ambiguity that results. (I don't mean to be the one pushing Linked Data since it seems I get push back whenever that concept comes up, but I don't think the above switch asks users on either end to know anything more about Linked Data)

**Comment by mfenner** [comment]
In some vocabularies `agent` is the superclass for `person`, `organization` and possibly other things, e.g. [FOAF](http://xmlns.com/foaf/spec/#term_Agent). Therefore I would prefer the term `person` here. Also consider that ORCID IDs are for people and not other agents. I use this at DataCite to help determine whether an author is a person or organization (this is important for name parsing/formatting, e.g in citations).

I would hope the description of roles could be cleaned up a little bit, e.g. using the schema.org `Role`: http://blog.schema.org/2014/06/introducing-role.html. I have not used that property myself, but it seems it could be helpful here, e.g. by attaching additional properties to the role. This could be another alternative to the current implementation.

**Comment by cboettig** [comment]
Re `person` vs `organization`, I believe we chose the term `agent` explicitly because we want to include both options.  (For instance, a university could be the copyright holder).  

However, there's no reason we need the term `agent` to accomplish this inclusivity: schema.org 's [SoftwareSourceCode](https://schema.org/SoftwareSourceCode) already states that `copyrightHolder`, `contributor` etc has expected type that can be either `Person` or `Organization`.

Thanks for pointing us to the `Role` type, I'd forgotten about that.  Personally I find that description (and the JSON-LD [examples in the docs](http://schema.org/OrganizationRole) very confusing.  It looks like the role type is still a node name and not a value, e.g. instead of something like `"role": "member"`, you do:

```
  "member": {
    "@type": "OrganizationRole",
    "member": {
    "@type": "Person",
    "name": "Alice"
    },
```

which is pretty opaque to me.  For our case, this seems like instead of doing: 

```
"author:" {
  "name": "Carl Boettiger",
  "email": "cboettig@ropensci.org"
}
```

We'd have to do:

```
"author:" {
 "@type": "Role",
    "author": {
    "@type": "Person",
    "name": "Carl Boettiger",
    "email": "cboettig@ropensci.org"
}
```

It sounds like the only reason we'd want to do that is if we wanted to specify some additional property about the role, e.g. that Carl was the maintainer between `startDate` and `endDate`.  I don't think we've highlighted any use cases where the `Role` itself requires such further annotation (all the examples seem to be about role durations).  But I do think we need to revisit the way we have "agent" so that roles are properties of Software performed by people/organizations, but not properties of people.

**Comment by gothub** [comment]
@cboettig A consideration for the current `agent` structure with `role` is that it allows the
codemeta document author to use whatever namespaced vocabulary they want, and not be
limited to one schema that may or may not be difficult to add roles to. Here is the namespaced
example from the repo:
```
 "agents":[ {
        "@id": "http://orcid.org/0000-0002-2192-403X",
        "@type": "person",
        "email": "slaughter@nceas.ucsb.edu",
        "name": "Peter Slaughter",
        "role": {
            "namespace": "http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode",
            "roleCode": "contributor"
        },
...
```

**Comment by cboettig** [comment]
@gothub Right, the current agent model allows for more flexibility in role terms, though there are of course downsides to that flexibility as well : e.g. it looks likely that it will lead to lots of different ways of stating "contributor" via different namespaces, where arguably `contributor:` would be preferable.  Did we have compelling use cases for other roles?

If we do want this to be flexible, I think we still need to rethink it in such a way that the semantics make sense. The current semantics do nothing to connect the role to the software for which that role is performed, so we're not technically saying what we mean to say.  We would have to add something to the `role` section that referred to the software `id` for this to make sense, and I think that's a lot more cumbersome than defining the role as a node name.

**Comment by cboettig** [comment]
Relying on schema-defined roles, plus explicit additional roles in the `codemeta` namespace (currently just: "maintainer") for now.  Using additional CRediT roles is still an open issue, #47, best coordinated with other projects.  Meanwhile, I think we've closed this out.
