### ISSUE TITLE
drop isAutomatedBuild ?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#136]
@gothub I'm not entirely clear what `isAutomatedBuild` should mean. Can you give some examples? 

Does this suggest a nightly binary is somehow built automatically, e.g. via a CI system or something like Docker Hub?  I'm also not clear what the significance of this is.  I suppose it could be a measure of code quality, comparable to having a CI system in place, or perhaps of security (people look for the 'automated build' tag on Docker images to know it was built by Docker Hub and thus the image contains precisely what is says in the Dockerfile, instead of being some randomly edited binary).  But I don't see the term in the crosswalk table and don't really think it has a definitive use.  Maybe we consider dropping this term?

**Comment by gothub** [comment]
@cboettig The term `isAutomatedBuild` not being in the crosswalk might be an oversight, and not 
necessarily an indication of it being considered for deletion.

I don't remember who proposed this term, but I think the intent was that this term is associated with `contIntegration`, to indicate that the code has a high `vitality` and that the software could be easily built or binaries are available for a set of platforms, thereby supporting reproducibility and reuse.

**Comment by cboettig** [comment]
adopted in #142 proposal
