### ISSUE TITLE
Mapping to Wikidata properties

### ISSUE THREAD

**Issue by emulatingkat** [codemeta/codemeta#138]
Thank you for your work, Codemeta! I recently heard about your project. I am a volunteer contributor to Wikidata. A group of Wikidata contributors have been working on data modeling for the domain of Informatics https://www.wikidata.org/wiki/Wikidata:WikiProject_Informatics. 

Would your group be interested in mapping an additional column of data for Wikidata properties that describe software/ code?

I'd be happy to help out.

**Comment by mbjones** [comment]
@emulatingkat Definitely interested.  We're also looking at maximizing compatibility with the https://schema.org/Software model as well.  Have you looked over our [codemeta JSON-LD vocabulary](https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld)?

**Comment by emulatingkat** [comment]
@mbjones Thank you for your reply. I just took a look at the JSON-LD vocabulary. I hadn't explored that part of CodeMeta's work yet.

Would it be acceptable for me to open pull requests to suggest Wikidata property mappings?

**Comment by mbjones** [comment]
@emulatingkat Probably the best thing would be to PR a new mapping column to our [crosswalk table](https://github.com/codemeta/codemeta/blob/master/crosswalk.csv), which shows the relationship to many other vocabularies.  Then we could discuss how to incorporate new concepts into the JSON-LD schema via additional PRs.

**Comment by cboettig** [comment]
Resolved by PR #143
