### ISSUE TITLE
Syed Omar Faruk Towaha: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by SOFTowaha** [codemeta/codemeta#14]
<p><br><blockquote>This issue was created by @SOFTowaha via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbjones** [comment]
Hey Syed -- glad to see your interest in the codemeta project.  We have lots to do in the project, so let us know where you'd be interested in contributing.  Pull requests are welcomed.

**Comment by SOFTowaha** [comment]
Thanks @mbjones .
