### ISSUE TITLE
adopt schema:provider in place of codemeta:packageSystem ?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#140]
A couple issues I think we want to address with `codemeta:packageSystem`.

Current (v1) context types this as an `xs:string`,  though in practice we seem to use urls (e.g. `https://cran.r-project.org` rather than `CRAN`).  A more informative type might be `Organization`, which could then have a name, url or other information associated with it.  In this case, one could still give a url, which would be interpreted as an `@id` of a node, e.g.

if one had:

```json
{
"packageSystem": "https://cran.r-project.org" 
}
```

one could also optionally specify

```
{
"@id": "https://cran.r-project.org",
"@type": "Organization",
"name": "Central R Archive Network"
}
```

Which would be the functional equivalent of:

```json
{
  "packageSystem": {
    "@id": "https://cran.r-project.org",
    "@type": "Organization",
    "name": "Central R Archive Network"
  }
}
```

Does this sound appropriate?

An alternative strategy might be to adopt a term already in `schema.org` instead of introducing `packageSystem`, e.g.  https://schema.org/provider (part of `CreativeWork` type inherited by both `SoftwareApplication` and `SoftwareSourceCode`).  Both `publisher` and `provider` are already expected type `Organization` (though in v1 of the schema we've typed `publisher` as `xs:string`).  

Preferences?  Any feedback much appreciated.

@gothub @arfon @kyleniemeyer @acabunoc @danielskatz @mbjones @mfenner others

**Comment by mfenner** [comment]
I like `publisher` and `provider`, not sure which one I would pick here.

**Comment by cboettig** [comment]
Thanks @mfenner .   I'm leaning towards `provider` because I think it's less ambiguous.  e.g. imagine a ruby gem or R package that's developed on github and archived on zenodo with a DOI, but distributed through a "provider" registry like CRAN or rubygems.org.  Given that zenodo provides the DOI, from an academic sense they are likely to be considered the "publisher", right?

**Comment by mfenner** [comment]
For something on GitHub, CRAN and Zenodo the `publisher` discussion could get a bit tricky, even more so if the GitHub repository is owned by an organization such as `rOpenSci`. I would do a pragmatic decision now (e.g. use Zenodo as publisher if there is Zenodo DOI) and then see whether there can be a community discussion on this (if it hasn't already).

**Comment by cboettig** [comment]
dropped `packageSystem` for consistency with schema.org, recommended way to specify a package `provider` is `provider` (e.g. `codemetar` implementation will automatically indicate the `provider: https://cran.r-project.org` for packages provided by CRAN).
