### ISSUE TITLE
Improving the crosswalk table

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#141]
The current implementation of the crosswalk table can be a bit difficult to extend or work with.

For instance, from our table, it's not obvious that `package.json` in nodejs has a notion of `author` and `contributor` but no notion of `maintainer` or `copyrightHolder`, or that it uses only `name` and not `givenName`.  Basically I think the challenge arises because some Concepts are node types / complex classes with a rich set of potentially implicit properties (`agent`), while others are simply properties.  

I've taken a go at creating a table in which the first column contains the possibly relevant schema.org properties from SoftwareApplication, SoftwareSourceCode, Person, Organization, types, along with those properties proposed by codemeta which have no analog in schema.  Thus every row is a property.  I've also kept the columns from schema.org giving the Type and Description of the properties, though it's not clear those are always helpful. (some of these could be rewritten to be more specific to the software case). See: https://github.com/codemeta/codemeta/blob/master/crosswalk_v2.csv

Also, as you've surely noticed, it cab be hard to read the crosswalk table.  I've been playing around with a quick update of the website, and created a couple pages corresponding to crosswalk columns that can show just how that given column maps onto codemeta properties.  (I use a bit of R code to subset).  Because we can drop unmapped terms, this results in more concise, readable tables, see: http://codemeta.github.io/crosswalk/ 

@gothub @mfenner @kyleniemeyer @arfon @mbjones  @danielskatz @acabunoc  Thoughts on this version and the website visualization?  (If this approach sounds promising I'd like to update `crosswalk.csv` to `crosswalk_v2.csv` **soon**, since it would be greatly preferable if pull requests could be made against the newer version.)

**Comment by arfon** [comment]
@cboettig - I can't find `crosswalk_v2.csv` in the repository. This is the list of files I see:
<img width="1005" alt="screen shot 2017-05-13 at 7 58 59 am" src="https://cloud.githubusercontent.com/assets/4483/26025283/206f5c32-37b2-11e7-92d7-b3b85186b4a2.png">

Perhaps you mean [`crosswalk-v1.csv`](https://github.com/codemeta/codemeta/blob/master/crosswalk-v1.csv)?

I like what you've done with the website - this is really helpful way of seeing the properties mapped onto other formats. Seeing this makes me wonder whether it might be worth trying to build a small service that can parse an existing resource (e.g. RubyGem URL) and return a codemeta representation of the metadata... 🤔

**Comment by cboettig** [comment]
Sorry about that, I renamed v2 to just plain crosswalk.csv since I think it has all the same content and I wanted to avoid getting PRs against the old table. Maybe that was bad form.

Hehe, glad you like the web display.  What's the status of the ruby parser?  I have a draft R parser at https://GitHub.com/codemeta/codemetar, might be good to link these from their crosswalk pages.

**Comment by moranegg** [comment]
@cboettig I really like the new version of the crosswalk table with the ParentType column and the option on the website to visualize each mapping to CodeMeta terms.

In [Software Heritage](https://www.softwareheritage.org/) we plan on extracting metadata from files, identified by a filename pattern, that are likely to contain metadata and parsing the terms using the crosswalk table.

Tools like codemetar are a real asset, so I'm for linking the crosswalk page to the actual tool.

**Comment by mfenner** [comment]
@cboettig I like what you have done. @arfon I also thought about a parser for Rubygems. I have built a Rubygem that could be extended to do that, as it already handles codemeta (and bibtex and a few others): https://github.com/datacite/bolognese. I could work on that in June.

**Comment by cboettig** [comment]
Web-based vis of the updated `crosswalk.csv` live on website, `crosswalk.csv` now reflects terms from the v2, schema-aligned context (as well as v1).
