### ISSUE TITLE
schema.org property in place of codemeta:softwarePaperCitationIdentfiers ?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#144]
@mfenner Thought you might have a solid suggestion here.  The codemeta property `softwarePaperCitationIdentifiers` is pretty cumbersome. Do you feel that `schema:citation` is preferable here?  Software isn't really "citing" the software paper.  Maybe `schema:relatedLink`?(which is listed only a property of `schema:Webage`...)

Alternately we can stick with defining our own term (`codemeta:softwareArticle`?), though it would be far more consistent if it wasn't typed as Text/URL but rather as `schema:SoftwareArticle`, so the user could supply either an id (DOI) or an inline SoftwareArticle description.

**Comment by mfenner** [comment]
You could something like this to describe the link to the paper citing the software:
```
"@reverse": {
    "citation": {
      "@id": "https://doi.org/10.1016/s0022-2860(03)00179-0"
    }
  }
```

**Comment by mfenner** [comment]
It this is the paper describing the software, you might rather use: 
```
"@reverse": {
    "isBasedOn": {
      "@id": "https://doi.org/10.1016/s0022-2860(03)00179-0"
    }
  }
```

**Comment by cboettig** [comment]
Thanks.  I see your point about lacking explicit `reverse` properties.  Still, I think we need a different term to capture the concept of a paper describing the software (e.g. the equivalent of a CITATION file in an R package mentioning a paper).  The above formulation is too easy to confuse with a list of all papers that cite the software.

**Comment by alee** [comment]
We've been oscillating between  `associatedPublication` and `referencePublication` in our own internal metadata as we rewrite the openabm.org computational model library. Leaning towards `referencePublication` at the moment but we're open to other suggestions!

**Comment by cboettig** [comment]
thanks @alee , I do like`referencePublication`

**Comment by cboettig** [comment]
Current proposal is to to introduce the `referencePublication` into codemeta.  Not sure it's perfect, but existing schema terms look just too ambiguous to me.  I think we try this out for the moment and see how it goes.
