### ISSUE TITLE
Author ordering: should we set @container to @list ?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#146]
JSON-LD arrays are un-ordered by default, matching the expectation of a graph in linked data, though opposite from the default in plain JSON, see [docs](https://json-ld.org/spec/latest/json-ld/#sets-and-lists)

The mechanism to indicate than an array should be ordered is to set the value of the container to list: `"@container`": "@list"` (the default is `"@set"`).  This is usually done in the context definition, e.g.

```json
  "author": {
      "@id": "schema:author",
      "@container": "@list"
    }
```

but can also be done in the data itself,

```
"author": { 
          "@list": [
             { 
               "familyName": ...
              }
              ....
              ]
```

Alternately (and perhaps more robustly), `CreativeWork` includes the property `position` which is defined in Schema.Org as "The position of an item in a series or sequence of items."   This approach is compatible with a simple default context like `"https://schema.org` being used by DataCite etc.   

@mfenner, I see you use `position` in the [DataCite JSON-LD representation](https://github.com/datacite/bolognese) in citation list, but not for authors?

So, do we want to encourage the use of "position" in `author` metadata?  Would we rather change the container value to list?  Do both?  Seems like we want a consistent strategy for author ordering in related efforts using JSON-LD, cc @arfon @danielskatz

**Comment by mfenner** [comment]
Excellent point, need to think about it. Most people assume authors are an ordered list, so we should probably model that.

**Comment by danielskatz** [comment]
+1

**Comment by alee** [comment]
I like the implicitness of `@list` . Also, `position` has the potential for ambiguous data - what do you do with two entries with the same `position`?

**Comment by cboettig** [comment]
Sounds good to me.  I've set codemeta-v2.jsonld to use `@list` as the container.  This way users can merely continue to assume that author list is ordered and not pay any attention to this technicality, while the context will make sure any JSON-LD routine is aware that author is a `@list`  not a `@set`.

@mfenner Do you think that would work for your end on DataCite etc too?  Would require a little extra in your `context` but should otherwise be a straight-forward update?

**Comment by mfenner** [comment]
@cboettig that should work for DataCite.
