### ISSUE TITLE
some last questions on aligning codemeta.jsonld with schema

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#147]
Hey @gothub (and anyone else who wants to chime in) ,Just wanted you to give me one last sanity-check me on two remaining details in our codemeta.jsonld file.  These are technical issues and probably don't make a much difference either way, but wanted to at least document the issues here.

### pure extension model

First, I'm pretty happy with the way we've explicitly named each term from schema.org which we feel is appropriate for the codemeta context, but I just wanted to point out this is probably not the *usual* way of extending schema.org (really we're extending it with codemeta, but also greatly restricting the context as well).  The more standard strategy seems to be pure extension, so that all of schema.org is part of the context; and is usually done with an array for the `@context`, e.g.

```
"@context": [ { "customTerm": "codemeta:customTerm", ... }, "http://schema.org"]
```

Unlike all other arrays in json-ld, order matters here, and so putting <http://schema.org> last in this array makes it the default vocabulary for any unrecognized term.  I don't *think* we want to go this route, (we'd rather be restrictive).  Agreed?

### matching schema.org's context types

One of the more natural  and useful features of having our context aligned with schema.org is that a user can jsonld_expand a codemeta file, and then compact it using only the `schema.org` context.  This could be useful for applications that have already been designed to consume pure `schema.org` data.  Codemeta terms obviously wouldn't compact, but would be left with the `codemeta:` prefix.  (this can be run in reverse to, you can compact, say, a DataCite json-ld file into the codemeta context).  

However, any term in which the `type` declaration differed in `schema.org` context vs codemeta would fail to compact.  For instance, if CodeMeta context declared: 

    "datePublished": "schema:datePublished"

this property it would not compact into pure `schema.org` because the [schema.org context file](http://schema.org/docs/jsonldcontext.json) explicitly types date fields as:

        "datePublished": { "@id": "schema:datePublished", "@type": "Date"},

As you can see in schema's context file, Dates are one of the very few cases that are explicitly typed.  Declaring a type in codemeta when it is untyped in schema creates the same problem.  

So, the upshot of this is that if we are not doing the nesting thing in issue 1, it may pay to be very careful to match type declarations that schema.org context does and doesn't declare.  schema.org never declares the type for either Text-valued properties (description, keywords) or node-valued ones (author, editor), while it seems to always declare URLs as `"@type": "@id"`, which seems a bit surprising (even though an id is indeed a URL).  Currently we still have a handful of mismatches relative to schema.org types.  

(Note that the pure-extension strategy sidesteps this issue entirely)

**Comment by gothub** [comment]
@cboettig 

I've always thought that we are extending the codemeta schema with schema.org, so I'm in
favor of the more restrictive `@context` declaration that doesn't allow for using any schema.org
term, so codemeta documents are 'required' to use the set of terms we have agreed on for
describing software.

If instead we think of codemeta as a typical schema.org extension, then maybe it might be useful
to revisit the schema.org 'sanctioned' (recommended?) extension mechanisms. I'm not
proposing that we go through their review process for an 'official' extension, but maybe reviewing
this again will inform how to proceed with our current schema.

For the extension mechanisms briefly described at http://schema.org/docs/extension.html, I think our 'model' is closest to the 'external' one mentioned.

**Comment by cboettig** [comment]
Thanks Peter!  Good, let's go with the more restrictive context.  

Like you say, that page seems to be more about the review process to get the blessing/approval of schema.org team (either for them hosting or for an external schema), which I don't think we're concerned with at the moment.  I'm guessing schema.org team would rather just add a few codemeta properties into core schema.org for their existing SoftwareApplication and SoftwareSourceCode types.  I think our main goal is just to be maximally compatible with their namespace; like you've said the whole compaction/expansion crosswalk needs this common notion.  

So, since we're declaring them explicitly, shall I'll take a pass at making sure all of our type definitions for schema.org match those in http://schema.org/docs/jsonldcontext.json ?

**Comment by gothub** [comment]
@cboettig yep, good idea.
