### ISSUE TITLE
spelling differences in Node.js crosswalking and homepage missing

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#149]
In Node.js/NPM crosswalking the term used is bundledDependencies, I was just looking at some package.json files and discovered bundleDependencies without the d is a popular and discovered that:

> "If this is spelled "bundleDependencies", then that is also honored." (https://docs.npmjs.com/files/package.json)

is this something we want to make note of? by adding both spellings into the crosswalk?

Also, I will do a pull-request to add homepage as url for Node.js.

**Comment by cboettig** [comment]
Thanks, yeah, we could add both spellings (comma separated in the crosswalk cell).  And adding hompage.  A PR for this would be great

**Comment by moranegg** [comment]
oh sorry, i was to quick to PR only the homepage addition.

**Comment by cboettig** [comment]
never too late! if you just push any additional changes to the branch you made the PR on, they become part of the current PR.

**Comment by moranegg** [comment]
great!
thanks for the help PRing :-D
