### ISSUE TITLE
Crosswalk to US code.gov metadata schema

### ISSUE THREAD

**Issue by npch** [codemeta/codemeta#159]
@lhsu-usgs noted that US Agencies are required their inventories using a standard metadata schema:

https://code.gov/#/policy-guide/docs/compliance/inventory-code

It looks like this would be easy to crosswalk and they have sample JSON files and a validator (from that page)

**Comment by cboettig** [comment]
Very nice, thanks!  Yup, looks like it would be a straightforward one for us to crosswalk.

**Comment by cboettig** [comment]
aggregating these
