### ISSUE TITLE
Recommended fields & levels of metadata, from Neil's wssspe piece

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#16]
http://figshare.com/articles/Minimal_information_for_reusable_scientific_software/1112528

**Comment by band** [comment]
Nice article. But the downloaded document not contain a date or suggested citation. This hinders understanding the context in which it was written and sharing it with others.

**Comment by npch** [comment]
@band - I'm the original author of this document, which was a working document for a workshop.

At present I'm in the process of addressing reviewer comments on an extended version of the document submitted to the Journal of Open Research Software. If accepted, this would have both a published date and suggested citation.

**Comment by band** [comment]
@npch Thanks for the note and publication outlook. I have some thoughts about the paper and deriving metrics based on your work. (Re-)usable data sets share many of the same or similar properties.

**Comment by npch** [comment]
@band would love to hear your thoughts on the subject!

**Comment by mbjones** [comment]
Are there any particular outcomes from this ticket in terms of changes to the crosswalk table?  If not, we can probably close it, noting that we should cite the paper by @npch in our crosswalk piece, if it has come out yet.  A pointer to that would be useful, @npch...
