### ISSUE TITLE
Version and SoftwareVersion

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#162]
In the CodeMeta terms we can find both, schema:version and schema:softwareVersion.
the first from CreativeWork and the latter from SoftwareApplication.

What's the difference?

Does anyone uses both for different entries?

**Comment by cboettig** [comment]
Yup, they are both inherited from schema.org, so excluding one would just make codemeta unnecessarily incompatible with other schema.org SoftwareApplication descriptions.  Schema.org usually seems to avoid creating this kind of duplication though, so I'm not sure how softwareVersion slipped in (technically `version` is typed to be either numeric or text data, `softwareVersion is only text).  

I always stick with `version`; haven't seen much use of `softwareVersion`.
