### ISSUE TITLE
Support for name prefixes and name suffixes

### ISSUE THREAD

**Issue by npch** [codemeta/codemeta#169]
The codemeta schema does not currently support name prefixes (e.g. the "von" part) and name suffixes (e.g. the "Jr." part).

The issue is that the Person schema in schema.org (and most citation systems) only uses "givenName" and "familyName".

I propose that this isn't fixed in the schema but that the documentation suggests that schema:Person:identifier is the preferred field, and then that can be used to deference the preferred format of the name (and thus the givenName and familyName fields are really only there for human consumption).

**Comment by cboettig** [comment]
I second this.  Best for `codemeta.json` to include ORCID ids whenever possible.  Codemeta has helped encourage native support for ORCIDs in R package metadata:

![](https://pbs.twimg.com/media/DLr14xAW0AIZMqr.jpg)

**Comment by cboettig** [comment]
person identifiers seem to be the way to go here.
