### ISSUE TITLE
Interested in contributing to project

### ISSUE THREAD

**Issue by npch** [codemeta/codemeta#17]
I've been working in this area for a while, can contribute to discussion and documentation, trial and review code and docs, hack code (slowly).

**Comment by acabunoc** [comment]
Thanks @npch! And thanks for your comments in #16 :)

**Comment by mbjones** [comment]
Hey @npch -- @cboettig, @mbjones, and @arfon are putting together a project to get interoperability among repositories with respect to software metadata.  We're going to hold a workshop to crosswalk approaches and work on this early next year.  Hope you're able to join us.

**Comment by npch** [comment]
@mbjones - would love to. Have some previous experience of exposing software metadata using DOAP from doing work to make UK e-Science project metdata scrapable by @rgardler 's Simal.

**Comment by froggleston** [comment]
We'd love to be part of this! We're developing a federated linked-data-aware data submission and publication platform (https://github.com/TGAC/COPO) for plant sciences and would love to work with and contribute to the spec! :)

(We being myself, @shaw2thefloor, @tonietuk, @agbeltran)

**Comment by rgardler** [comment]
I'm not in a position to do any work directly on this but if some of the lessons from Simal as mentioned by @npch can be of use I'd be happy to share thoughts. Feel free to ping me.
