### ISSUE TITLE
multiple programming languages?

### ISSUE THREAD

**Issue by stevengj** [codemeta/codemeta#181]
How does a `codemeta.json` file indicate that a project uses multiple programming language?  I couldn't find any examples of this.

**Comment by mbjones** [comment]
Probably repeat the `programmingLanguage` term in the document.  CodeMeta doesn't constrain the cardinality of term usage.  And I don't think that is a problem under schema.org either.

**Comment by cboettig** [comment]
Yup, other than `@id`, just about any field can take an list of values and still be valid.

**Comment by stevengj** [comment]
In general it would be good to have a human-readable document describing the fields and the possible values in each, along with an indication of which fields are most common/important. 

Examples only go so far.

**Comment by cboettig** [comment]
Hi @stevengj ,

You want a list value, e.g. `"programmingLanguage": ["R", "python"]`.  Most JSON validators will flag a repeated key as a syntax error. 

Thanks for your suggestion regarding documentation, as you've seen we're not always good at knowing what's most helpful for a new user, or how to make what is available more "discoverable", so your advice would be great.

For instance, there's a document describing all the fields here: https://codemeta.github.io/terms/ .  As almost all terms correspond to those use by schema.org, there is also: http://schema.org/SoftwareSourceCode.  (Of course neither one of these would have answered your question above!  For that, maybe examples would be more helpful.  I also highly recommend the JSON-LD specs over at https://json-ld.org/, the authors made a fantastic effort to make these way more accessible to non-specialists than the average W3C spec.)

As to which are "most important", that's a bit more subjective based on your use case.  Someone wanting to study dependency graphs may have a different criterion than someone who wants merely to better facilitate software citation.  Our goal is merely to provide a common mechanism for expressing these things, not to dictate what to express.  On the flip side, if there's a concept you feel is important but lacking from the codemeta context, please let us know!

**Comment by stevengj** [comment]
Thanks.
