### ISSUE TITLE
Codemeta for Python packages (pip/pypi/distutils)

### ISSUE THREAD

**Issue by proycon** [codemeta/codemeta#182]
As far as I know, there was no tool yet to convert metadata associated with Python packages (pip/pypi/distutils) to codemeta. I therefore started to work on this, analogous to what *codemetar* does for R, and have a first prototype available: https://github.com/proycon/codemetapy . It is designed to parse ``pip show -v`` output but has various extra abilities as well. I hope it may prove a valuable addition to this interesting project.

**Comment by proycon** [comment]
Yes, definitely! That would be very nice

**Comment by cboettig** [comment]
now linked, closing this.
