### ISSUE TITLE
Should codemeta.json be delivered with software?

### ISSUE THREAD

**Issue by rettinghaus** [codemeta/codemeta#187]
I was wondering if the codemeta file should be included in a software distribution package, or merely is for the repository holding the source code. 

Overall the documentaion and user guide could be improved with more examples.

**Comment by cboettig** [comment]
@rettinghaus Good question.  I think it would be ideal to distribute the `codemeta.json` file with the software distribution, but I think it is ultimately up to the developer to answer this.  For instance, in some cases doing so would violate the software spec -- for instance, R packages do not permit arbitrary files to be included in the repository root.  While there are other ways around this, the most common approach is to list `codemeta.json` in `.Rbuildignore`, such that it does not end up being included in the distribution one would get from the CRAN (the usual distribution network); e.g. see https://github.com/ropensci/codemetar

I totally agree the documentation could be improved and should include examples!  Still, it is a bit of a challenge not to make these too prescriptive.
