### ISSUE TITLE
how to generate codemeta.json from python

### ISSUE THREAD

**Issue by danielskatz** [codemeta/codemeta#190]
I know there's a python tool to generate a codemeta.json file, but it's not listed on https://codemeta.github.io/tools/ or http://codemeta.github.io/user-guide/

Also, that tool does not generate a file that includes ORCIDs, which it probably should

**Comment by cboettig** [comment]
@danielskatz indeed, still needs to be done (duplicate of #182). 

Re ORCIDs in python version, maybe you can open an issue at https://github.com/proycon/codemetapy/issues ?

Thanks!
