### ISSUE TITLE
Definitive sources for crosswalk terms

### ISSUE THREAD

**Issue by brucellino** [codemeta/codemeta#193]
Hi!
I am preparing a PR to the crosswalk table to add a new term (see #191). It's a bit difficult to know whether the term I want to add is covered by existing schema without knowing where to look for all of them.
Could a header or comment be added to the csv table to link to the documentation of the various schema?

Thanks
Bruce

**Comment by cboettig** [comment]
@brucellino Good question, we probably do need to document this more clearly, at least for folks not already very familiar with JSON-LD.

The definitive source is really https://doi.org/10.5063/schema/codemeta-2.0, i.e. the JSON-LD context file for codemeta.  The csv table is a bit looser as a format, (e.g. doesn't declare types), so is really more documentation than it is a formal statement of existing schema.  More background on writing context file on https://w3c.github.io/json-ld-syntax/#the-context, but I think you'll find it pretty straight forward; e.g. adding a new term that would be unique to codemeta and be text valued would be something like: 

```
      "networkRequirements": { "@id": "codemeta:networkRequirements" }
```

or if it can also be specified as a URI it would be:

```
      "networkRequirements": { "@id": "codemeta:networkRequirements", "@type": "@id" }
```

.

**Comment by brucellino** [comment]
Thanks @cboettig !
My issue was around checking if the other endpoints in the crosswalk actually implement the term. So I needed to go to the various schema documentations and see. This took a bit of time, especially since I don't use many of them on a daily basis.

It would be useful to have a link - perhaps on the public page - that says "If you want to add a term, you're going to have to check the following schema:" and then a list of documentation pages for them.

**Comment by cboettig** [comment]
Ah, good call, I see what you mean now.  

Yeah, it would be nice to have an easy way to crosswalk all the existing schema against a new term; I think that is easier to do for some than others.  I wish there was a less manual way to do that, but for many of them there really isn't a nice single page defining all permitted terms!  Still, there probably is more we could provide to make it at least a little easier.  Suggestions / PRs welcome!

**Comment by brucellino** [comment]
Ok - I think it would be more appropriate to send PRs for this to codemeta/codemeta.github.io, where the rest of the documentation is. I'll therefore close this issue and open another against that repo.

**Comment by cboettig** [comment]
👍 agreed.
