### ISSUE TITLE
Chicken/egg problem: need to include DOI in metadata, but want citation file in release to get DOI?

### ISSUE THREAD

**Issue by kyleniemeyer** [codemeta/codemeta#24]
I'd like to start including a citation metadata file following the codemeta standard with my software, but I'm a bit confused about what appears to me to be a chicken/egg problem: the codemeta schema wants an identifier (e.g. DOI)—but in order to get a DOI for my (GitHub) repo, I need to create a release of the software.

So, I'm a bit confused about the appropriate process here... if I create a release to get the DOI, it would be missing the full metadata associated with that release.

**Comment by technocrat** [comment]
Hi Kyle,

Could you do a 0.0.1 release consisting solely of a readme and still get the DOI?

**Comment by kyleniemeyer** [comment]
That could be one solution, but really each release of the software should be associated with a different DOI, so that someone can cite a particular version that they used.

Taking a quick look at Zenodo where releases from GitHub can get DOIs, I see examples of this being done: [julia v0.4.0](https://zenodo.org/record/31957?ln=en) vs. [julia v0.4.0-rc3](https://zenodo.org/record/31528?ln=en).

**Comment by mbjones** [comment]
There are mechanisms to get a DOI before making a product available through an embargo period. Zenodo may not support this, but EZID and DataCite do, and it's used commonly to embed a DOI in the metadata of a data set or article before it is released. Seems to me that Zenodo could support a similar process.

**Comment by lnielsen** [comment]
On Zenodo we do support reserving a DOI prior to upload. It's however not available through the GitHub-feature, but only through the manual upload.

**Comment by kyleniemeyer** [comment]
@lnielsen oh that's great to know, thanks!
