### ISSUE TITLE
Link to continuous integration service

### ISSUE THREAD

**Issue by agbeltran** [codemeta/codemeta#243]
Codemeta currently has a ```contIntegration``` term with type URL and definition ```link to continuous integration service```.

This issue proposes to expand the label to ```continousIntegration``` and consider changing the definition to ```Link to the instance of the continuous integration service for the software code being described.``` The type would remain as URL, and an example value is https://travis-ci.org/github/codemeta/codemeta

This doesn't change the previous intention but provides more clarifications on what should be included. There is no property to indicate what is the continuous integration service being used (Travis, Jenkins, etc) and that would need to be deducted by the user (but we are not planning to provide this as a machine readable element unless there is a strong requirement to do so in another property). 

No other vocabularies seem to include this. See further analysis at: https://docs.google.com/document/d/1R1zFMYY9uRUzLkYS70m5u63W1Ig-iJ1L6oVVwyY5p6g/edit

**Comment by moranegg** [comment]
I agree with having the longer term `continuousIntegration`.

I would suggest the following definition with an example:
> Link to the instance of the continuous integration service for automation workflows (e.g Travis, Jenkins, etc.)

**Comment by arfon** [comment]
:+1: to the more readable `continuousIntegration`.

**Comment by dgarijo** [comment]
+1 to `continuousIntegration` for consistency (e.g., `developmentStatus` is not `devStatus`)

**Comment by mfenner** [comment]
+1 by the Force11 Codemeta Task Force regarding `continuousIntegration`.

**Comment by tmorrell** [comment]
Implemented in PR https://github.com/codemeta/codemeta/pull/258

**Comment by moranegg** [comment]
Further discussion will be dine on #258

**Comment by progval** [comment]
Merged! (through #302 , which is #258 with merge conflicts resolved)
