### ISSUE TITLE
update CONTRIBUTING guidelines with review process

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#253]
After talking with @mfenner and @moranegg we agreed that clarifying the process for submission, review, and acceptance of changes to CodeMeta would be helpful.

**Comment by moranegg** [comment]
We should create in the coming month a new repository called `governance` to indicate this information

**Comment by progval** [comment]
Created: https://github.com/codemeta/governance

**Comment by moranegg** [comment]
We have updated the CONTRIBUTORS file with PMC and contributors for each version.
The CONTRIBUTING file does not need to change.

We will update README for v3.0 to make it clear that we have the PMC now.
