### ISSUE TITLE
Interest in this project

### ISSUE THREAD

**Issue by zoidy** [codemeta/codemeta#26]
Hi all, 

I'll throw my hat in the ring and say that I'm willing to contribute to this project, as I've found it useful in my investigations regarding research software preservation. I've made some updates to the crosswalk that I'm willing to share, though I can open separate issues/pull requests for those.

In the mean time I have a quick question about the crosswalk. Is there a reason that 'version' is not included in the Codemeta column even though it's there in the codemeta.jsonld, or is it just an omission?
-Fernando

**Comment by mbjones** [comment]
Hi @zoidy -- welcome to the group.  And thanks for the version issue, I just fixed that oversight for codemeta in sha aff90a3, but I will have to look at the other standards for more information for the rest of the mapping.  And we'd welcome pull-requests if you have specific suggestions.
