### ISSUE TITLE
crosswalk table `type` and `schema`

### ISSUE THREAD

**Issue by tmorrell** [codemeta/codemeta#261]
Does it make sense to have lines 57 and 58 'schema	type' and 'schema	id' in the crosswalk table? These are dependent on what term they are attached to, so having just one line for them doesn't really make sense. They have also not been filled out, except for one entry in CFF. Is it alright to remove these lines?

**Comment by cboettig** [comment]
:+1:

**Comment by tmorrell** [comment]
Implemented in PR #262
