### ISSUE TITLE
targetProduct

### ISSUE THREAD

**Issue by tmorrell** [codemeta/codemeta#267]
CodeMeta currently includes schema:SoftwareSourceCode/targetProduct and schema:SoftwareApplication/operatingSystem. These seem very similar, but operatingSystem seems clearer and no one has crosswalked targetProduct. Would it make sense to remove targetProduct from v3?

**Comment by cboettig** [comment]
@tmorrell I believe these are very different.  My reading is that in this context, targetProduct is the software product _created by_ the source code, e.g. the binaries (possible multiple entries for different operating systems and architectures).   

I agree that scientific software (and related schemas, including those from package management systems) makes less use of targetProduct than in the commercial settings like app stores  that schema.org obviously cares about. All the same, I think it can be a useful distinction.  Make sense?

**Comment by proycon** [comment]
I just wanted to emphasize that I'm adhering to the reading suggested by @cboettig in my implementations (in [codemetapy](https://github.com/proycon/codemetapy) and derived tools), so I definitely wouldn't like to see this disappear from v3. However,  the current schema.org description is indeed rather vague and @tmorrell 's interpretation would be more in line with it. I earlier tried to open some discussion on it in #271 .

**Comment by moranegg** [comment]
Hi, I'm closing this issue since we are keeping targetProduct.
