### ISSUE TITLE
Codemeta generator: inconsistencies in management of fields with multiple values

### ISSUE THREAD

**Issue by frmichel** [codemeta/codemeta#307]
Hi there, 

I'm using the [codemeta generator](https://codemeta.github.io/codemeta-generator/) and experience a few issues with fields that can take multiple values, in particular funder and referencePublication.

If I st funder as this:
```
    "funder": [
        {
            "@type": "Organization",
            "name": "org1"
        }, {
            "@type": "Organization",
            "name": "org2"
        }
    ],
```
the import function simply ignores the values. Is it to say that it is invalid or this is just a pb with the generator?

Also, I can import this:
```
    "referencePublication": [
        "https://hal.science/hal-123456",
        "https://hal.science/hal-654321"
    ],
```
But when I regenerate the codemeta it is turned into this:
```
    "referencePublication": "https://hal.science/hal-123456,https://hal.science/hal-654321",
```

So in the end, can we add arrays of values anywhere or only with some specific fields and which ones?

Thx for your help.

**Comment by progval** [comment]
> can we add arrays of values anywhere

Yes.

This is a limitation of the codemeta-generator so it doesn't get too complicated

**Comment by frmichel** [comment]
Ok cool, thx for your super quick reply! ;)

**Comment by frmichel** [comment]
Just a remark: I've also tried on the affiliation of an author, but here the generator explicitly says that an array value is invalid. Couldn't it be an array too?

**Comment by progval** [comment]
Yes, it could

**Comment by frmichel** [comment]
Would be cool to fix these issues in the generator, when you guys have a bit of time ;)

**Comment by dgarijo** [comment]
Yeah, I found a similar thing with descriptions. If you have more than one the generator will tell you it's not valid. But it should be (e.g., i can have short and long description, or descriptions in more than one language)

**Comment by frmichel** [comment]
Thx @progval.

**Comment by moranegg** [comment]
Thanks for the lively discussion and feedback. Closing this issue.
@frmichel feel free to open issues on the other side at https://github.com/codemeta/codemeta-generator/issues
