### ISSUE TITLE
References / Background reading

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#31]
- GitHub Guide on 'citable code' via Zenodo Integration https://guides.github.com/activities/citable-code/
- NIH vision for a Software Discovery Index: http://www.softwarediscoveryindex.org/
- This is a DataCite-based schema to represent software: http://rrr.cs.st-andrews.ac.uk/wp-content/uploads/2015/10/guidelines-software-identification.pdf

**Comment by mbjones** [comment]
Background reading added to agenda:  https://codemeta.github.io/agenda
