### ISSUE TITLE
Choose identifier for the CodeMeta schema

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#321]
I'm using this issue as a duplication of a email thread on the codemeta-pmc mailing list.
It was initially launched with the v2.1 release to discuss and vote the v3.0 identifier.

@mbjones wrote in the exchange: 
Ideally we should: 
1) when requesting JSON-LD, get the context file directly; 
2) when requesting HTML, get the documentation page for the terms, and 
3) have individual term identifiers resolve to anchored term definitions when HTML is requested.

The options suggested and provided in the pmc exchange:
A. https://w3id.org/codemeta (Thanks @dgarijo !):
From the conversation:
- curl -sH "Accept:application/ld+json" -L https://w3id.org/codemeta/ will get you the JSON. 
- If you resolve https://w3id.org/codemeta/ in your browser, it will take you to https://codemeta.github.io/terms/
- Version ids are supported: 
[https://w3id.org/codemeta/{version}](https://w3id.org/codemeta/%7Bversion%7D). 
- For example https://w3id.org/codemeta/1.0. I redirected the HTML of the versions to https://codemeta.github.io/terms/ because as far as I know there is no versions on the HTML.
- It's open: https://github.com/perma-id/w3id.org/tree/master/codemeta

B. https://purl.archive.org/purl/codemeta/2.0 (Thanks @cboettig !)
- widely used in other vocabularies
-  the ids are not open, i.e., you can't have several maintainers on an id
- limited content negociation capabilities in [purl.org](http://purl.org/). For example, it does not support content negotiation on content type (JSON-LD vs HTML)

C. new DOI
- I won't list advantages and drawbacks because it seems clear that this is not what we need for using the vocabulary.

With this discussion we should also approach a few experts in the semantic artifacts domain to see what are the requirement of the vocabulary identifier.

We will go ahead and use the w3id, if there is no community feedback before September 6th.

**Comment by moranegg** [comment]
September 6th is behind us.
We can move forward with the identifier: https://w3id.org/codemeta

**Comment by stain** [comment]
The current [JSON-LD context](https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld) maps to  https://codemeta.github.io/terms/ as namespace, yet implied term URIs like https://codemeta.github.io/terms/maintainer do not currently resolve. Relying on deployment details like `github.io` in a namespace is also not good practice.

Should this then not use PID namespace https://w3id.org/codemeta# instead?   You can then add `id="maintainer"` etc. in the HTML so also human browser get the definition. (and perhaps some javascript can do highlighting of selected row)

**Comment by dgarijo** [comment]
@stain I raised this in https://github.com/codemeta/codemeta/issues/216 a few years ago. Completely moving to w3id may bring in incompatibility changes for those registries that have adopted codemeta, so I understand it may be trickier... but I would still go for it

**Comment by moranegg** [comment]
I agree and need some community feedback for the best solution with the identifier and  resolution.
I see we agree on w3id for the ID.
Now we need to agree on the redirection. Let's see if we get answers before October 15th.

**Comment by moranegg** [comment]
Hi @dgarijo,
In this [folder](https://github.com/perma-id/w3id.org/tree/master/codemeta) do we need to change the redirection before updating this information on this repo?

Thanks for the help.
Best,
Morane

**Comment by ljgarcia** [comment]
Even though all issues related to the redirection are not yet (?) resolved, I am happy to see the namespace. Will start using it for our extension on properties related to Software Management Plans (that might bring suggestions for new properties).

**Comment by dgarijo** [comment]
@moranegg no changes are needed. If you want to change the link to the latest version, you only need to change the link in the htaccess which now points to https://raw.githubusercontent.com/codemeta/codemeta/3.0/codemeta.jsonld. Or ping me with the right file and I will change it in a sec
