### ISSUE TITLE
Add `standard` or `standards` field to CodeMeta

### ISSUE THREAD

**Issue by bact** [codemeta/codemeta#349]
More software supply chain documentation, quality management, and legal transparency requirement require a software package to declares relevant standards that may apply to the software.

SPDX:
- `standards` property in SPDX 3.0 Core
- "The relevant standards that may apply to an artifact."
- An artifact can have 0 and more standards.
- https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/standard.md
- https://github.com/spdx/spdx-3-model/blob/main/model%20Core%2BSoftware.png

EU AI Act draft (26 Jan 2024) requires AI providers to list relevant technical standards:
- Requirements for high-risk AI systems -- Article 11(1), detailed in Annex IV (6)
  - "Annex IV (6) A list of the harmonised standards applied in full or in part the references of which have been published in the Official Journal of the European Union; where no such harmonised standards have been applied, a detailed description of the solutions adopted to meet the requirements set out in Title III, Chapter 2, including a list of other relevant standards and technical specifications applied;" 
- Obligations for providers of high-risk AI systems -- Article 17(1)(e)
  - "technical specifications, including standards, to be applied and, where the relevant harmonised standards are not applied in full, or do not cover all of the relevant requirements set out in Chapter II of this Title, the means to be used to ensure that the high-risk AI system complies with those requirements;"
- https://data.consilium.europa.eu/doc/document/ST-5662-2024-INIT/en/pdf

--

I propose we have a `standard` or a `standards` field, with `Text` or `URL` type.

**Comment by progval** [comment]
I feel that is outside the scope of Codemeta, "minimal metadata schema for science software and code", we are not aiming for all the expressiveness of SPDX in matters of compliance.

**Comment by bact** [comment]
Thank you. I will close this issue for now.

Maybe in the future when there's more need in the scientific community for this type of data (measurement/calibration standards, etc) we can reconsider it as necessary.
