### ISSUE TITLE
CodeMeta descriptions in a machine-readable format?

### ISSUE THREAD

**Issue by tpronk1** [codemeta/codemeta#355]
Hey CodeMeta,

I would like to make a table of terms in software-metadata with a description per term, including the CodeMeta vocabulary. For this purpose I seek descriptions in a machine-readable format.

I noticed the JSON-LD file of schema.org features fields as illustrated below with person. Is there any JSON-like file for CodeMeta that contains such descriptions? 
`"rdfs:comment": "A person (alive, dead, undead, or fictional)."`

Thanks,
Thomas

**Comment by progval** [comment]
what about https://github.com/codemeta/codemeta/blob/master/properties_description.csv ?

**Comment by tpronk1** [comment]
For our current purposes, the table provided by @progval will do the trick; thanks! For the rest this is indeed a duplicate of #323, so let me close this issue
