### ISSUE TITLE
Schould we add crossswalk to npm (JavaScript)?

### ISSUE THREAD

**Issue by acabunoc** [codemeta/codemeta#40]

**Comment by acabunoc** [comment]
Done by @lukecoy here: https://docs.google.com/spreadsheets/d/1Xm45UQRBO6Ru7IF5cXYdz84YFrTa28mhukEweZGmw1U/edit#gid=1338407015

Luke, can you link to the doc you used to create the mapping?

**Comment by lukecoy** [comment]
:+1: 

Documentation used for mapping: https://docs.npmjs.com/files/package.json

**Comment by mbjones** [comment]
NPM crosswalk merged from Group B table.

**Comment by acabunoc** [comment]
According to the doc @lukecoy linked, these fields are required in npm:
* name
* version
