### ISSUE TITLE
Should we crosswalk to ADMS.SW?

### ISSUE THREAD

**Issue by npch** [codemeta/codemeta#41]
The [Asset Description Metadata Schema for Software](https://joinup.ec.europa.eu/asset/adms_foss/home) "is a metadata vocabulary to describe software making it possible to more easily explore, find, and link software on the Web. The specification reuses existing specifications, such as DOAP, SPDX, ISO 19770-2, ADMS, and the Trove software map. By using ADMS.SW to describe software in software forges, repositories, and catalogues, publishers increase discoverability and enable applications easily to consume software metadata."

However I'm not sure if anyone actually started implementing it.

**Comment by ceefour** [comment]
:+1: for this. I wonder why there's not much interest. I think ADMS.SW is the closest to CodeMeta, and interoperability (or better: incorporation ) of it would be a great benefit. It's an European Commission formal standard that's mature.

See discussion in https://github.com/WhiteHouse/source-code-policy/issues/117
Any suggestions @konklone @JJediny @philipashlock @benbalter @jhourcle ?

**Comment by cboettig** [comment]
aggregating list of additional schema in one place to avoid stale open issues
