### ISSUE TITLE
Should we crosswalk to Trove?

### ISSUE THREAD

**Issue by npch** [codemeta/codemeta#45]
The Trove software map is used in many different commercial software repositories and catalogues.

Originally developed by Sourceforge, it's not available from the original location [https://sourceforge.net/api/trove/index/rdf](https://web.archive.org/web/20120628144255/http://sourceforge.net/api/trove/index/rdf) so I have linked to the archive.org version.

**Comment by acabunoc** [comment]
Done by @npch here: https://docs.google.com/spreadsheets/d/1Xm45UQRBO6Ru7IF5cXYdz84YFrTa28mhukEweZGmw1U/edit#gid=1338407015

**Comment by mbjones** [comment]
Merged into join.csv.
