### ISSUE TITLE
Should we crosswalk to Perl packages? (CPAN)

### ISSUE THREAD

**Issue by acabunoc** [codemeta/codemeta#50]

**Comment by acabunoc** [comment]
See our results here: https://docs.google.com/spreadsheets/d/1Xm45UQRBO6Ru7IF5cXYdz84YFrTa28mhukEweZGmw1U/edit#gid=1338407015

We used these to build the mapping:
https://metacpan.org/pod/CPAN::Meta::Spec
http://www.cpan.org/scripts/submitting.html

**Comment by mbjones** [comment]
This is merged into the main join.csv, but some of the perl-specific concepts were reviewed and marked for deletion.  Need to review and make decisions before closing.

**Comment by acabunoc** [comment]
I completely support the removal of any Perl specific concept

**Comment by cboettig** [comment]
Looks like this wasn't closed once perl was merged in.  Closing
