### ISSUE TITLE
Add mapping to the Software Ontology

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#6]
The Software Ontology (SWO) has similar classes.  Add this to the mapping table.

See `doi:10.1186/2041-1480-5-25` at http://www.jbiomedsem.com/content/5/1/25

**Comment by sbpcs59** [comment]
The paper http://www.jbiomedsem.com/content/5/1/25 describes the process of creating the SWO, and
some of the fields considered were not implemented in the ontology. Table 1 shows that some
properties were not "bought" or accepted at the workshop. So, I've only added properties into the crosswalk that were implemented 
in the ontology. The ontology was downloaded from https://sourceforge.net/projects/theswo/files - which is contained in 'swo_core.own' which imports the other SWO ontology component own files.

**Comment by gothub** [comment]
SWO was added to the crosswalk with commit 3b48130e4491031f4f5d3f156a31b4a13fd35962
