### ISSUE TITLE
GitHub crosswalk additions/adjustments

### ISSUE THREAD

**Issue by arfon** [codemeta/codemeta#66]
Assuming that the GitHub fields are mapping to the [repositories](https://developer.github.com/v3/repos/#get) API I have some comments/suggestions for modification:

| Concept | Current | Suggested | Comment |
| --- | --- | --- | --- |
| `SoftwareIdentifier` | `id` | `full_name` | More descriptive but potentially less stable? |
| `RelatedLink` | --- | `homepage` |  |
| `ZippedCodeLink` | --- | `archive_url` |  |
| `ProgrammingLanguage` | --- | `languages_url` |  |

**Comment by arfon** [comment]
/ cc @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Just submitted #69 to resolve this.

**Comment by cboettig** [comment]
this was merged but never closed.
