### ISSUE TITLE
synergies with libraries.io

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#75]
@arfon pointed me to http://libraries.io which has an implementation of a very codemeta-spirit project for crawling standard package repositories and aggregating their data such as dependencies, versions, and so forth.  

For instance, here's their parser for crawling R-package DESCRIPTION files on CRAN and extracting metadata: https://github.com/librariesio/librarian-parsers/blob/master/lib/parsers/cran.js

The metadata model seems somewhat minimal, for instance, that script seems to focus only on dependencies, I don't see any author / title metadata parsing in that `cran.js` parser.  (The CRAN dependency parser was only just implemented, so this data is not yet up on the landing pages).  

They seem to be parsing GitHub data separately, and the landing pages for the packages show mostly data extracted from that (e.g. authors, title, etc as reported by GitHub, rather than the DESCRIPTION file).  

I think they are also parsing the CRAN html records separately.  For instance, compare the records of a package that is on CRAN & GitHub (testthat: https://libraries.io/cran/testthat) to one that is on CRAN but not GitHub (Matrix: https://libraries.io/cran/Matrix):

**Comment by cboettig** [comment]
@mbjones @sbpcs59 see https://github.com/librariesio/librarian-parsers/issues/15#issuecomment-214511476

**Comment by mbjones** [comment]
@cboettig This is a great project.  What specifically should we do on codemeta to interface with them?  We certainly should cite them in our paper....  other things, or can this ticket be closed?

**Comment by cboettig** [comment]
I wondered if it would be worth actually directly comparing how our crosswalk stacks up against their implicit crosswalk (same could also be true for Depsy, but I don't think they released the source for their crawlers).  Their crawlers for different software databases could also suggest additional columns that are not in our table.  

Ultimately it would be ideal if their crawler system first populated a database of codemeta.json files for each software piece in it's index, and then generated their data summary from that.

**Comment by andrew** [comment]
@cboettig @mbjones creator of https://libraries.io here 👋 

I can potentially add a codemeta.json endpoint for each library and github project that I have indexed so far, about 1.5 million libraries and 8 million open source GitHub repositories, for example:

https://libraries.io/npm/base62.js/codemeta.json 

The librarian-parser code you linked to is only used for pulling out the dependency info for a github repo, most of the meta data is parsed using this ruby code: https://github.com/librariesio/libraries.io/blob/master/app/models/repositories/cran.rb

And then extra data is added if it can make a connection to a GitHub repository (and in future a bitbucket, gitlab or sourceforge repo)

Maybe it would be worth arranging a google hangout/skype chat to discuss anyways that I can help the codemeta project?

**Comment by andrew** [comment]
Forgot to mention that there's a JSON API for Libraries.io here: https://libraries.io/api

I'm also going to be applying for a grant from MOSS (https://wiki.mozilla.org/MOSS/Mission_Partners) which feels like a really good alignment with is project.

**Comment by arfon** [comment]
> Maybe it would be worth arranging a google hangout/skype chat to discuss anyways that I can help the codemeta project?

👋 @andrew. This sounds like a great idea. I suspect Matt and Carl are pretty focussed on finalizing the schema right now but adding something along these lines to the Libraries API would be ✨
