### ISSUE TITLE
Minimal fields (to enable software citation & author credit)

### ISSUE THREAD

**Issue by arfon** [codemeta/codemeta#76]
During the codemeta workshop in Portland a few of us sat down and tried to work through what is the _absolute minimal_ set of fields to enable software citation and author credit. I'm afraid I've managed to loose my note from this discussion but I believe we settled on the following (pulling field names from https://github.com/codemeta/codemeta/blob/master/crosswalk.csv):

```
AuthorId
SoftwareIdentifier
Version
```

We discussed the fact that `Version` might not always be available and that `datePublished` would be a worse-but-better-than-nothing-alternative.

Thoughts on this?

**Comment by band** [comment]
Arfon, the fewer fields that are required, the better chance there is that contributors will provide the information.

One question: ORCiD is provided as an example of an AuthorId. Is there a similar example for SoftwareIdentifier?

dataPublished seems like a good alternative for Version.

**Comment by arfon** [comment]
> Arfon, the fewer fields that are required, the better chance there is that contributors will provide the information.

👍 absolutely.

> One question: ORCiD is provided as an example of an AuthorId. Is there a similar example for SoftwareIdentifier?

I think this could be something like repository address (e.g. https://github.com/codemeta/codemeta). What do you think?

**Comment by kyleniemeyer** [comment]
Wouldn't we want to use DOI for SoftwareIdentifier?

**Comment by arfon** [comment]
> Wouldn't we want to use DOI for SoftwareIdentifier?

Ideally. But what if there isn't one...?

**Comment by mbjones** [comment]
I don't think we should be proscriptive; a DOI or other global identifier would be best; a github URI to a tagged release is probably next best, and then a github URI to a repo (which loses version info).

**Comment by mbjones** [comment]
@arfon Do we want to mark these fields as required for software citation in the crosswalk table?  Or how do we indicate the minimal required set of fields for any given use case?

**Comment by arfon** [comment]
> @arfon Do we want to mark these fields as required for software citation in the crosswalk table? Or how do we indicate the minimal required set of fields for any given use case?

I'm in two minds here. We could mark them in the crosswalk table or we could just provide examples that demonstrate these minimal fields.

Do we have other 'minimal' fieldsets for other usecases outside of software citation/author credit?

**Comment by ljhwang** [comment]
To complicate factors, are we heading towards a tiered system as minimal really is just that and it would be great to push people towards more complete metadata specifications. For example, is there minimal, recommended (best practices), target/desired metadata ?

**Comment by owlice** [comment]
Authors (of papers and software both) often like to aggregate citations to one entity; requiring the version number in a citation may preclude that (depending on the citation, indexer, etc.). I would say _AuthorId_ and _SoftwareIdentifier_ is the absolute minimal set. These fields allow both software citation and author credit.

**Comment by mbjones** [comment]
I think 'title' should also be in the minimal list for the citation/credit use case.

**Comment by owlice** [comment]
A lot of code citations do not include “title”, which I think would be really useful, but from citation practice, appears unnecessary. Examples of ASCL citations that do not include “title” yet make it possible to find the code entry and track the citation:

http://iopscience.iop.org/article/10.1088/0067-0049/221/2/24/meta#references
Plez B. 2012 Astrophysics Source Code Library ascl:1205.004
Bizyaev D. and Shetrone M. 2015 Astrophysics Source Code Library ascl:1502.022
Hubeny I. and Lanz T. 2011 Astrophysics Source Code Library ascl:1109.022

http://mnras.oxfordjournals.org/content/444/4/3975
Cooper M. C., Newman J. A., Davis M., Finkbeiner D. P., Gerke B. F.  Astrophysics Source Code Library, record ascl:1203.003. 2012.


When papers are cited, their titles are often not part of the citation; this blog post about the various ways codes are cited shows some examples. I’m sure I can find examples of code citation by DOI, but I’m almost out of juice so will have to do that later tonight or this weekend. I have a big ol’ Google doc that has lots on citation and will look in that, too. 

From this exchange, though, maybe we need more than “author” and “identifier” — in many cases for whatever is being cited, perhaps we also need the source of the identifier, whether a journal designation, domain repository, Zenodo, etc.

Alice

**Comment by ljhwang** [comment]
Interesting. I would advocate that people use a “title” in a citation which has more recognition than an identifier.

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D.
Associate Director, CIG
530.752.3656

**Comment by kyleniemeyer** [comment]
I agree with @ljhwang—I can't imagine citing software and not giving the name of what I used.

From a truly "minimal" perspective, you probably don't need anything more than a unique identifier—but we usually include titles and other information for papers in addition to DOI (depending on the citation style, of course).

**Comment by owlice** [comment]
In thinking about this, here “identifier” is a generic rather than specific term — anything that can uniquely identify a particular resource (in this case, a code or software package) that is by a particular person. So the identifier could be title or name of the code, DOI, ASCL ID, etc. 

Alice

**Comment by owlice** [comment]
It’s quite common for those using ASCL entries to not list the name of the software. I didn’t come up with this citation method, BTW; it’s what the community came up with! (What ASCL initially suggested, which included the code name, was completely ignored.) I definitely like it when a citation includes the name of the software (I think it makes the reader’s job easier), but if we are to come up with a minimum set, practice — at least in astro — clears shows it is not required if there’s another identifier such as a DOI/ASCL ID/etc. Surely there are examples from other disciplines of this being the case, yes? No?

**Comment by mbjones** [comment]
This concept of 'minimum' is a bit misleading, in that what we are really talking about is recommended practice.  If a given community like astro decides to exclude the title, then that's really fine and up to them.  But I propose that we would have widespread agreement that the __recommended__ fields for citation should include:

- Author (name + ID) (in codemeta, this is an "Agent" with "mustBeCited==true"
- Identifier
- Title
- Version
- Publication Date

Here's what this would look like in CodeMeta JSON syntax (from [this file](https://github.com/codemeta/codemeta/blob/master/examples/example-codemeta-citation-rdataone.json)):

```json
{  
   "@context":"https://raw.githubusercontent.com/codemeta/codemeta/master/codemeta.jsonld",
   "@type":"SoftwareSourceCode",
   "identifier":"http://dx.doi.org/10.5063/F1M61H5X",
   "datePublished":"2016-05-27",
   "title":"dataone: R Interface to the DataONE REST API",
   "agents":[
      {  
         "@id":"http://orcid.org/0000-0003-0077-4738",
         "@type":"person",
         "email":"jones@nceas.ucsb.edu",
         "name":"Matthew B. Jones",
         "mustBeCited":true
      }, 
      {  
         "@id":"http://orcid.org/0000-0002-2192-403X",
         "@type":"person",
         "email":"slaughter@nceas.ucsb.edu",
         "name":"Peter Slaughter",
         "mustBeCited":true
      }
   ],
   "version":"2.0.0"
}
```

Compare this to the more complete [codemeta record for rdataone](https://github.com/codemeta/codemeta/blob/master/examples/example-codemeta-rdataone.json) to see all of the other fields that could have been provided.

**Comment by npch** [comment]
I'll play devil's advocate here.

Let's say I put up a piece of code which represents my implementation of a particular piece of functionality, but I don't consider to be a full piece of software so I don't think to name it. But it becomes widely used and people want to cite it.

In this case, it has Author, Identifier, Version (I've been good) and Publication Date, but the title is what other people refer to it as "Implementation of heuristic email scraper for identifying researcher emails" / "Improved email scraper" / "Academic email address scraper" etc.

Are we saying here that we are recommending all authors provide a title for all pieces of their code they assign an identifier to?

In practice, I realise that current infrastructure to provide an identifier mostly requires provision of a title, but as we move towards micro-citations, does this still hold up?

**Comment by ljhwang** [comment]
Point well taken.

It begs the question of what gets an identifier. Is it a piece of a larger code base or collection? Is it a snippet (random or not) that can stand on its own? 

As it is a “recommendation” and not a requirement, I guess it would be up to an author to decide how she wants it refer to in conversation/literature. Most of us do give code a name besides “main”. Clearly over time I can remember my own personal ID numbers, but no one may recognize it as such. I have also seen where authors have named code (or renamed) in retrospect as usage has exceeded expectations.

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D.
Associate Director, CIG
530.752.3656

**Comment by mbjones** [comment]
Fair enough, I agree that may happen, and @owlice has given some good examples, even though pretty much every piece of software has at least a filename that could provide some context.  But it isn't our main case, its an edge case at best. We are talking about recommended norms for citation, not what might happen in a worst case scenario.  My contention is that, if someone is going to the trouble of generating a codemeta description of the software, then they should be able to figure out a reasonably descriptive title that at least let's people know what roughly the software is about (i.e.., "Implementation of heuristic email scraper for identifying researcher emails" is perfectly fine).

**Comment by cboettig** [comment]
This is a great thread, but I think the codemeta project should defer to the Software Citation Implementation group to advise on this issue: https://github.com/force11/force11-sciwg (Thanks @danielskatz @mfenner and others) .  Deciding precisely what metadata fields must be associated with a use case seems beyond the scope of codemeta.

**Comment by mfenner** [comment]
Thanks @cboettig. I opened an issue in the Force11 Software Implementation WG repo: https://github.com/force11/force11-sciwg/issues/5.
