### ISSUE TITLE
add COmputational INfrastructure for Operations Research to crosswalk

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#77]
From Alice Allen:

> It occurs to me that I need to turn in expense documentation and I will do that this weekend (I swear!), but that’s not why I’m writing. I ran into the COmputational INfrastructure for Operations Research website tonight; it is, possibly approaching was, a software repository. 
> 
> Metadata for this project: 
> Name, project description, project manager, project home page, project license, linked COIN-OR projects [linked name], third-party software [package, required/optional], programming language, development status (activity status, maturity level [0-5], stable version number, stable release number), builds and passes unit test on (operating system, compiler), project categories, This is an umbrella project for the following sub projects: [nested bulleted list]
> 
> Sample entries:
> http://www.coin-or.org/projects/jMarkov.xml
> http://www.coin-or.org/projects/Ipopt.xml
> http://www.coin-or.org/projects/GAMSlinks.xml
> http://www.coin-or.org/projects/Cgl.xml
> 
> I’m not suggesting you do anything with this information except know that it’s yet another research software metadata example.

**Comment by cboettig** [comment]
aggregating these
