### ISSUE TITLE
Merge use case columns in crosswalk.csv

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#78]
The crosswalk currently has 3 columns with crosswalk numbers from the old list
of 14 use cases (1 column each from each break out group). Map these to the new 6 use cases from the [use case summary](https://github.com/codemeta/codemeta/blob/master/CodeMetaSoftwareUseCases.md) and merge into one column.

**Comment by kyleniemeyer** [comment]
I believe that @npch and I were going to tackle this—I can take it on.

**Comment by sbpcs59** [comment]
@kyleniemeyer sounds good, thx
