### ISSUE TITLE
DateModified

### ISSUE THREAD

**Issue by RichardLitt** [codemeta/codemeta#8]
Does this refer to the code itself, or to the metadata? What provisions are there for editing metadata? Say that I have to update my email - how can I do that? 

This isn't clear to me at the moment, but I may be missing something.

**Comment by cboettig** [comment]
As I understand it, JSON-LD context mechanism doesn't actually constrain the context as to where dateModified may be used, so in the current implementation it would be valid to put it in anywhere.  At the top level it would refer to the top-level node, but could be re-used to refer to an author node or any other node as well.
