### ISSUE TITLE
move manuscript into Git

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#80]
Current Google doc is here:
https://docs.google.com/document/d/1ftoKb1nI0kox-mgZEHafEieZg2Fsx92wKRi-vwJxmyU/edit?usp=sharing

Move to the paper repo, and modularize to allow parallel editing:
https://github.com/codemeta/codemeta-paper

**Comment by kyleniemeyer** [comment]
👍 I can take care of getting this done tonight! (Unless someone else already is)

**Comment by kyleniemeyer** [comment]
I just took all the text from the Google Doc and created an initial paper draft, with different files for the different sections. I don't have commit permissions for the paper repo, so I created PR codemeta/codemeta-paper#1

**Comment by mbjones** [comment]
Kyle moved it into git using RMarkdown.  Run with that for now.

**Comment by kyleniemeyer** [comment]
(I just want to put it out there that I would have used LaTeX, but @cboettig made it pretty clear he preferred RMarkdown... 😛)
