### ISSUE TITLE
What should the codemeta JSON file be named?

### ISSUE THREAD

**Issue by ctb** [codemeta/codemeta#81]
Working on a JOSS submission for https://github.com/dib-lab/sourmash, and want to add a codemeta JSON file. I generated one with @arfon's script here, https://gist.github.com/arfon/478b2ed49e11f984d6fb, but I don't know what to name it or where to put it in the repo. (Right now it's [paper.json](https://github.com/dib-lab/sourmash/blob/master/paper.json) which seems wrong ;). I can't find any obvious guidelines here - thoughts?

**Comment by cboettig** [comment]
I believe we've thought of it as being `codemeta.json`, (yeah that's also the name of the "schema" file in this repo, but in JSON-LD schema isn't really separate from the data file the way an xsd file is usually distinct from an xml file).

**Comment by ctb** [comment]
OK, that seems reasonable.  Is that documented anywhere, or should
I file a ticket / submit a PR, or does that better belong over in JOSS
if JOSS is asking for it?

(I can find e few xamples of a file named that with Google, but not many --
e.g. https://github.com/Starlink/pal/blob/master/codemeta.json)

**Comment by ctb** [comment]
FWIW, @arfon names it paper.json here: https://gist.github.com/arfon/478b2ed49e11f984d6fb

**Comment by stevengj** [comment]
It would be good if this were documented somewhere, e.g. in the user guide https://codemeta.github.io/user-guide/
