### ISSUE TITLE
Should there be a codemeta badge?

### ISSUE THREAD

**Issue by ctb** [codemeta/codemeta#82]
e.g. to stick in the README?

**Comment by mbjones** [comment]
@ctb Sounds like a good idea. Question is, what should it signal?  Providing a *minimal* codemeta document, as @arfon described in #76 ? Using *any* or *some* fields from codemeta?  Providing a *comprehensive* codemeta document, for some definition of comprehensive?

**Comment by ljhwang** [comment]
@mbjones. I think there is some thought to what is a minimal, as in bare bones, and what really should be included discussion which may influence what a badge means. I am leery of giving someone a badge for bare bones minimum.

**Comment by cboettig** [comment]
Badges usually link to something too, probably just a static page explaining codemeta in this case, but I suppose one could have a server crunch the json-ld and generate a badge indicating some level or numeric value (like code coverage or download count badges do).  Probably overkill at this stage, but just a thought.

**Comment by ctb** [comment]
The link could go to an HTML display of the codemeta.json contents, which
could then provide appropriate links (to ORCID, etc.)

**Comment by ctb** [comment]
well, at least at first, the fact that someone has *heard* of codemeta will
be a pretty good sign that they're thinking about this space.

and of course you can always change up what the badges mean over time -
provide a '% of important information filled in' badge and then change
the denominator over time.

badges would also provide an explicit measure of adoption - you could
use them to track how many people are actually using your stuff.
