### ISSUE TITLE
Relationship to BibJSON & citing papers/data/software dependencies

### ISSUE THREAD

**Issue by jonathansick** [codemeta/codemeta#83]
I'm interested in deploying JSON-LD across my [organization's repositories](https://github.com/lsst) both to aid citation of our work and as a metadata layer for internal project discovery and management. Naturally I'd like to build upon codemeta. Please bear with me, though, as I'm new to JSON-LD and metadata.

While researching JSON-LD I came across [BibJSON](http://okfnlabs.org/bibjson/) (which is also described in [a code4lib article](http://journal.code4lib.org/articles/7949)). The basic idea of BibJSON is to re-use the vocabulary of BibTeX keys in a JSON presentation for describing a resource. The BibJSON website indicates that BibJSON is compatible with JSON-LD.

This makes me wonder if there's a synergy between codemeta and BibJSON, which I haven't seen mentioned here.

On one hand, BibJSON may be a useful cross-walk target for codemeta (related to #58?).

On another, BibJSON also looks like a convenient way to include citations. For example, a software package may use third-party algorithms or datasets (or even direct software dependencies), and we'd want to cite those works. Given that those citations may already be available in a bibtex format, it seems easy to convert those bibtex entries into BibJSON objects and include them as an array in a JSON-LD document.

In general, I'm unsure how citations are intended to be made from codemeta JSON-LD. `RelatedPublications`, `SoftwareCitation`, and `SoftwarePaperCitation` also seem to be intended for describing papers that authoritatively describe the software, rather than being generic citations to third-party works. (correct me if I'm wrong here)

I'd be happy to hear about how citations should be represented in codemeta JSON-LD, and whether BibJSON could be a useful representation for cited entities. Thanks!

cc: @arfon @augustfly @aaccomazzi @dbouquin  @lnielsen and @libcce and who I've talked to about metadata strategies via email previously.

**Comment by cboettig** [comment]
Interesting idea, thanks.  Codemeta already crosswalks to DataCite, whose API already returns data I'm bibtex, (among other formats).  Cc'ing @mfenner who can comment better on those details, but at least we would want to be consistent with that mapping.  See 
http://crosscite.org/cn/#sec-4

On the other hand we probably don't want to get too into the weeds of just crosswalking bibliographic formats, since that may already be more-or-less done by others.

**Comment by cboettig** [comment]
In general I think we want to focus on software part of the crosswalk.  Crosswalking between bibliographic info in schema.org, bibtex, and the bazillion other bibliographic ontologies is really beyond our capacity and already being handled nicely be datacite etc.
