### ISSUE TITLE
generate codemeta specification docs

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#85]
Docs to be built:
- [x] CodeMeta Usage Guide
  - A tutorial-style document explaining how to build a simple codemeta.json file (including referencing the context file, and provides links to the CodeMeta concept specifications
- [x] CodeMeta Concept Specification
  - The name and definition of all codemeta concepts, along with a simple preamble describing its relationship to serializations and crosswalks
- [x] CodeMeta Developer Guide
  - An introduction to the codemeta project rationale and technology choices targeted at developers who wish to create tools for creating,validating, and consuming codemeta metadata

**Comment by cboettig** [comment]
I think we agreed that the "Concept Specification" needed to be unified to avoid the redundant / possibly conflicting https://github.com/codemeta/codemeta/blob/master/codemeta-json-schema.json vs https://github.com/codemeta/codemeta/blob/master/codemeta-concepts.md .  Ideally the latter should be generated from the former, and should be hosted at whatever URL we're using for the codemeta namespace, right?  

Currently looks like we claim this is https://codemeta.github.io/terms/ though of course nothing exists there yet.  Could generate a html page from the schema.  I believe this is something I volunteered to do, but I think Peter (@gothub) was going to go through the two versions first and make sure the Descriptions in the schema.json file are standardized / updated and reflect the Neil/Kyle synthesis?

Should I open a new issue for these things or is it easier to keep it here?

**Comment by gothub** [comment]
@cboettig Maybe a better solution than trying to keep these two files in sync is to remove
the 'descriptions' from https://github.com/codemeta/codemeta/blob/master/codemeta-json-schema.json entirely, as they are not strictly required by validation software that reads this schema file. In addition, i'd like to move this file to a subdir, possibly `./validation`, as this file is only an
auxiliary validation file. I'll edit and move this file, so that you can proceed with the html page.

**Comment by mbjones** [comment]
I think I agree with Carl that it would be better to generate the .md file
as documentation from the schema file -- so better to just keep the
definitions in the schema file and create a way to generate the needed
display format.

**Comment by gothub** [comment]
@mbjones @cboettig I'm voting for making the `codemeta-json-schema.json` file less prominent.
I will have a look at the JSON-LD Framing API that @cboettig mentioned at our last meeting,
to see if that can replace the `codemeta-json-schema.json` file with a more JSON-LD centric
validation tool, as Carl suspected. I'll update this issue once I have evaluated this API.

**Comment by cboettig** [comment]
I think the developer guide is basically our best documentation of the spec: 
 https://codemeta.github.io/developer-guide/

Our terms page provides a nice comprehensive list documenting what is in the context file.  https://codemeta.github.io/terms/
