### ISSUE TITLE
Review, approve, and tag/publish v1 of CodeMeta

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#86]
Review the spec, schema, and docs, approve, and tag release.
- [ ] Matt Jones
- [ ] Carl Boettiger
- [ ] Peter Slaughter
- [ ] Arfon Smith
- ...

**Comment by cboettig** [comment]
Yee haw! And http://doi.org/10.5063/SCHEMA/CODEMETA-1.0 now resolved!

**Comment by cboettig** [comment]
I suppose this is just pending #125 now.

**Comment by mfenner** [comment]
I had some minor issues when using codemeta metadata to mint two DOIs (https://doi.org/10.5438/qeg0-3gm3 and https://doi.org/10.5438/n138-z3mk). Where is the best place to provide feedback? Open up a GitHub issue for each issue?

**Comment by cboettig** [comment]
yeah, opening issues here for that sounds good to me

**Comment by cboettig** [comment]
Looks like v1.0 is tagged and published (and resolving now), right?

**Comment by mfenner** [comment]
Let me if there are any issues correctly resolving the DOI, but looked good when I checked again just now.

**Comment by mbjones** [comment]
Yes, as far as I see codemeta 1.0 is now shipped.  The DOI resolves to the schema content, which is tagged in the repo.  Thanks, everyone. Quite a milestone!
