### ISSUE TITLE
Formalize representation of software dependencies

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#90]
Here is a proposal for describing software dependencies. Feedback is welcome.

The CodeMeta context file currently defines the single JSON property 'dependency' to
express software dependencies for a package. This should be expanded so that dependencies
can be expressed in a more standard way. One possibility is to use "packageId", "packageVersion", "packageSystem", "operatingSystem" where
- packageId: the unique identifier for the package
- version: a character string indicating the build / state of the software
- packageSystem: the software or system used for packaging 
- operatingSystem: the platforms the package has been build and bundled for (optional)

for example:

```
   "dependency":[
         "packageId":"npplus",
         "version": "0.9.4",
         "packageSystem":"https://pypi.python.org",
      },
      {
         "packageId":"statistics",
         "version":"1.4.3",
         "packageSystem":"https://pypi.python.org",
      }
   ],
```

Another example:

```
   "dependency":[
      {
         "packageId":"abd",
         "version":"0.2-8",
         "packageSystem":"http://cran.r-project.org",
         "operatingSystem":"Windows, Mac OS X"
      }
      {
         "packageId":"popbio",
         "version":"2.4.3",
         "packageSystem":"http://cran.r-project.org",
         "operatingSystem":"Windows, Mac OS X"
      }
   ],
```

A value for `operatingSystem` is specified when required, for example, the operating system
isn't relevant for software distributed as Python packages or Matlab Central contributed
files, as those software packages are dependant on their execution environment (python, matlab)
and not the OS directly.

The `packageSystem` would serve as a namespace of sorts, as the values for `packageId`
and `operatingSystem` are specified as required by the `packageSystem`.

'version' would be optional and if omitted, the most currently available version would be  assumed.

**Comment by cboettig** [comment]
@gothub Looks great.  For operating system, I wonder if it would help to be a bit more specific. Also, how would you express what R at any rate calls 'system requirements' (think libxml2-dev or redlands), where the packageSystem might potentially be OS specific?  I imagine a programmatic installation of dependencies will remain beyond our scope, but I think we might take inspiration from what @gaborcsardi is doing with the R-Hub project in describing system requirements, https://github.com/r-hub/sysreqsdb

**Comment by gothub** [comment]
@cboettig The [sysreqsdb](https://github.com/r-hub/sysreqsdb) project looks great - where a requirement listed in the DESCRIPTION file is a key to a JSON db that includes all sub-requirements for the listed one. I'm thinking that the CodeMeta `dependency` has to stand alone however,
for simplicity. It also has to be able to describe any type of software, maybe even software that is not in a revisioned source code or build repository, i.e. figshare. The intent is to make the dependency description human readable and as helpful as possible, not necessary machine processable.

Do we want to provide a list of suggested values for `packageSystem` and `operatingSystem`,
maybe published in our documentation and checked by the instance file validator (yet to be
written)?

**Comment by gothub** [comment]
The dependencies as described about have been added to the context file and unit tests.
These still need to be explained fully in the documentation and included in the upcoming
verification tool. Added in commit 1a8238820448832587de29654e098758374272c8.

**Comment by gothub** [comment]
Added to the [CodeMeta Developer Guide](https://github.com/codemeta/codemeta/blob/master/developer-guide.md) in commit 2cff37d421fde13615295177c618e8374f5524d1

**Comment by mbjones** [comment]
One potential issue that I see with this format is that it separates out the package name from the version, which some packaging systems do not do.  

Also, it doesn't explicitly provide a mechanism to cite the `SoftwareIdentifier` that might have been used in a previous codemeta document for the software dependency.  Do we want to add that to allow citation chaining via the SoftwareIdentifier? Thoughts on that, @cboettig ?

**Comment by cboettig** [comment]
@mbjones right, that's an excellent point.  seems like we'd want to be able to refer to any dependency by an identifier directly.  I think we should change this to add that in.  

re separating out the version, can you give us some examples where they are not separated?  

Also, since I think our concept of version is permissive (xsd:string), potentially a hash or date could also be valid options?

**Comment by gothub** [comment]
I was thinking that the version and possibly the packageSystem would only be specified if required, e.g. for software that was uploaded to figshare, the packageId could stand alone, i.e. "https://dx.doi.org/10.6084/m9.figshare.2430685.v2", so version and packageSystem are not
required. For other software the version may required and may be listed separately from the packageId, if that is the convention for the packageSystem being referenced. For example, pypi
seems to list the packageId and version separately, and this is also shown in the DOAP record
for a project:

```
<rdf:RDF xmlns="http://usefulinc.com/ns/doap#" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<Project><name>npplus</name>
...
<release><Version><revision>0.9.4</revision></Version></release>
</Project></rdf:RDF>
```

**Comment by gothub** [comment]
The current dependencies look like this:
  
 "dependencies": [{
       "identifier": "http://doi.org/10.xxxx/A324566",
       "name": "export_fig",
       "version": "1.99",
       "packageSystem": "http://www.mathworks.com"
   }, {
       "identifier": "89766228838383883",
       "name": "npplus",
       "version": "0.9.4",
       "packageSystem": "https://pypi.python.org",
       "operatingSystem": ["Mac OS X", "Linux"]
   }]

Are any of these terms required? 

Can `identifier` be used alone?

**Comment by cboettig** [comment]
@mbjones Correct me if I'm wrong, but didn't we discuss including a namespace (or maybe that's the wrong term for it) for the identifier?

**Comment by mbjones** [comment]
I don't think so.  We said that the `name` was unique within the
`packageSystem`, but we didn't discuss identifier itself.  Most globally
unique identifiers now use a way of signaling the namespace in the syntax
of the identifier itself (e.g., DOI, Handle, urn:uuid, etc).  I think we
can reasonably rely upon that.

Regarding Peter's question about which are required: as JSON-LD doesn't
have a way of expressing cardinality constraints, I don't think anything is
truly required.

Matt

**Comment by gothub** [comment]
The software dependencies representation was reviewed on 12/22/2016 and deemed to be complete, without any additional changes.

**Comment by alee** [comment]
Hi there, I looked at the developer guide at https://codemeta.github.io/developer-guide/ but there is no mention of dependencies there - is that still part of codemeta or did those docs move somewhere?

**Comment by cboettig** [comment]
@alee Yes, the term `softwareRequirements` is part of codemeta and schema.org; codemeta also provides the additional term `softwareSuggestions` to distinguish between hard dependencies and other things (build dependencies , optional extensions etc).  The list of terms can be found in https://codemeta.github.io/terms/.  

side note: The developer guide is mostly focused on introducing the JSON-LD concepts, and doesn't describe all the terms themselves.  "developer guide" and "user  guide" should perhaps be renamed to "consume" and "create", since the dev guide is really aimed at developers who are writing tools that parse lots of codemeta files, not developers wishing to generate a codemeta file for their own software (which is what the user guide is supposed to cover).   Of course, feedback/edits/PRs on all of this more than welcome -- this is very much a community-driven project
