### ISSUE TITLE
Pulling dependencies from build systems?

### ISSUE THREAD

**Issue by encima** [codemeta/codemeta#93]
Could there be some modular approach to pull in dependencies from build systems for languages (I.e. npm for JavaScript, NuGet for C# or Cargo for rust). 

Would be keen to look into this if there was interest.

**Comment by mbjones** [comment]
@encima Yes, that would be interesting.  Note the longer discussion we've had on build dependencies in issue #90, where there are links to, e.g., the [sysreqsdb](https://github.com/r-hub/sysreqsdb) effort. At this point, we've decided to focus our requirements around being able to accurately enumerate and cite the dependencies, and not so much on being able to automate builds/imports across the diverse languages, as tempting as that would be.  If there is a clear and simple way to do that, I think we'd all be interested. But for now we've been focus on the more modest citable dependency use case.

**Comment by encima** [comment]
@mbjones that makes sense, I suppose not every build system will list dependencies in their format. Having it in the schema at least allows people to add them.manually and, I agree, the implementation for each build system does not seem like a huge priority right now.

**Comment by denis-yuen** [comment]
@encima We use dependency ci ( https://dependencyci.com/docs ) in some of our projects and it looks like it may depend on libraries.io which has open source parsers ( https://github.com/librariesio/librarian-parsers ) for various build systems, so that may be useful
