### ISSUE TITLE
Need to add Gitter link to README

### ISSUE THREAD

**Issue by kyleniemeyer** [codemeta/codemeta#95]
Rather than manage an email list, it might be easier to add a link to join the Gitter chat to the README.

(This is inspired by all the new people at WSSSPE4 who want to help out with CodeMeta, cc @owlice)

**Comment by mbjones** [comment]
@kyleniemeyer There is already a link at the top of the README to Gitter.  Did you mean something else?

**Comment by kyleniemeyer** [comment]
Huh sorry, not sure how I missed the badge! Nvm!
