### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kyleniemeyer** [codemeta/codemeta#96]
Based on feedback from WSSSPE4 working group members interested in CodeMeta, the README could use some updating to make the project more friendly to newcomers. 

(Alternatively, the Wiki could have some entries, including a roadmap. We should probably also create a CONTRIBUTING document.)

**Comment by sdruskat** [comment]
Could we have a "docs-draft" or "docs" branch to direct pull requests to, please?

**Comment by cboettig** [comment]
The Readme was significantly improved by @mbjones after this was posted, though could still use some tweaks.  Ultimately the (newly revised) website, https://codemeta.github.io, should probably be the best point of entry for new comers.  Some streamlining / tidying of the repo here will also help.  These are flagged in more recent, specific issues, so closing this one out.
