### ISSUE TITLE
Markdown files onto github.io

### ISSUE THREAD

**Issue by iaine** [codemeta/codemeta#99]
We should link the markdown pages in the codemeta.github.io pages to allow new users see the documentation on HTML rather than having to go through the repository. Perhaps create a documentation folder (i.e. docs) and move the documentation files to that folder and expose through there (like examples)? 

Also do the same for the existing examples folder so that the information is available?

**Comment by cboettig** [comment]
Agree.  codemeta.github.io now displays the csv tables from this repo (using Hugo's `GetCSV`), and we're migrating documentation over there.    

@gothub would be great to get your input on what in the `codemeta/` repo should be migrated, what needs to be updated, and what is stale and can be purged.
